### ISSUE TITLE
sf::IpAddress::IpAddress	(	const std::string & 	address	)	 broken

### ISSUE THREAD

**Issue by multivac3834** [SFML/SFML#1108] opened 2016-06-21 21:01 UTC
auto addr1 = sf::IpAddress::IpAddress(std::string("10.0.0.10").c_str());
	auto addr2 = sf::IpAddress::IpAddress(std::string("10.0.0.10"));

addr2 is zero

**Comment by LaurentGomila** [comment] 2016-06-22 05:40
I can't reproduce this. Can you give a complete and minimal example, as well as a description of your environment, and explain how you check the content of addr2?

Note that this kind of questions should be asked on the forum. We keep the tracker for confirmed tasks.

**Comment by Bromeon** [comment] 2016-06-26 09:41
Yes, please open a forum thread (in the Help>Network section). I'll close this issue for now.

**Closed by Bromeon** 2016-06-26 09:41 UTC
Labels: not an issue
