### ISSUE TITLE
Numpad Dot not in documentation.

### ISSUE THREAD

**Issue by JonathanILevi** [SFML/SFML#1596] opened 2019-07-02 02:43 UTC
The documentation does not have a key code for the numberpad dot.  Is this intentional?  It comes up as `Unknown` when it is pressed.  The same is true for the numlock and capslock key although this kinda makes sense.

Shouldn't there be a `NumpadDot` key code?

**Comment by minirop** [comment] 2019-07-02 08:11
I think NumpadDot is not a good name because it's not a dot, but a decimal separator (which is a comma in French for instance). Also, should SFML *convert* it depending of the locale? (like word/libreoffice do)

**Comment by JonathanILevi** [comment] 2019-07-02 15:00
Whether SFML should convert is another issue.

What would be a better name?  `NumpadDecimal`?

**Comment by MyrddinE** [comment] 2019-10-09 16:47
The code for getting keyboard events only has 101 entries; since modern keyboards usually have 106 keys or more this is not the only key affected. This should be resolved, both for simple convenience and for better accessibility for international and disabled users, who tend to be more likely to use uncommon keys.

**Comment by MyrddinE** [comment] 2019-10-09 16:51
Duplicate of #7

**Comment by oznogon** [comment] 2020-01-28 22:54
I'd argue for `Decimal`. For comparison, the [MinGW/Wine DInput headers](https://github.com/SFML/SFML/blob/ff011dc51dc47373b0d49b087f8ac9d3d2bc8b06/extlibs/headers/mingw/dinput.h#L579-L591) use `Decimal`, and SFML already (coincidentally?) aligns with those headers in naming numpad math keys `Add`, `Subtract`, `Multiply`, and `Divide`.

**Comment by eXpl0it3r** [comment] 2021-01-14 08:18
Scancodes will provide a lot more keys and keyboard layout independent. After the scancode implementation I'd be willing to look into expanding the existing `sf::Keyboard::Key` enum.

For now, I'll close this issue and point to the on going [Solution Design](https://github.com/SFML/SFML/wiki/SD%3A-Scancodes) and open PR #1235

**Closed by eXpl0it3r** 2021-01-14 08:18 UTC
