### ISSUE TITLE
Karabiner confuses Keyboard::isKeyPressed on MacOSX Sierra

### ISSUE THREAD

**Issue by TGlas** [SFML/SFML#1217] opened 2017-04-13 22:25 UTC
Since upgrading from MacOS 10.9 to 10.12 (Sierra), the function
`sf::Keyboard::isKeyPressed`
seems to always return false, at least for various keys I tried: shift, alt, and also letters. This worked before the OS upgrade. I tried SFML versions 2.0 (framework) and 2.4 (dylib); same behavior. Any ideas?

**Comment by mantognini** [comment] 2017-04-14 13:26
It works perfectly fine here. Try reinstalling SFML maybe... If the problem persists, please open a discussion thread on the forum with a SSCCE and all the details relative to your setup. Thanks.

**Comment by TGlas** [comment] 2017-04-14 15:34
The 2.4.2 version is a fresh reinall. I have worked around the problem with native cocoa call.

**Comment by soxfox** [comment] 2017-06-23 06:43
I have been getting the same issue with a fresh install of 2.4.2 on Sierra. I have tried framework and dylib, both manually and through brew. No matter what I try, `sf::Keyboard::isKeyPressed` returns false. Event based input works fine however.

**Comment by mantognini** [comment] 2017-06-23 06:50
What hardware do you have? (computer & keyboard model basically)

**Comment by soxfox** [comment] 2017-06-23 06:51
MacBook Pro Early 2011, with the built in keyboard.

**Comment by mantognini** [comment] 2017-06-23 07:14
Honestly, no clue what's going on... You could check that the key you're interested in is indeed registered here: https://github.com/SFML/SFML/blob/master/src/SFML/Window/OSX/HIDInputManager.mm#L272 (use a debugger, or add print statements + recompile, whichever you prefer). Check also that the program enters [this loop](https://github.com/SFML/SFML/blob/master/src/SFML/Window/OSX/HIDInputManager.mm#L367).

**Comment by niklaskorz** [comment] 2017-07-14 16:29
Same issue here. While checking for `sf::Event::KeyPressed` works as intended, using `sf::Keyboard::isKeyPressed` does not work at all.

**Comment by mantognini** [comment] 2017-07-14 16:53
I cannot reproduce this on my laptop. Please try to investigate on your side or this sadly won't be fixed.

**Comment by niklaskorz** [comment] 2017-07-14 17:01
No problem, I'll see if I can find something out

**Comment by TGlas** [comment] 2017-07-15 22:29
I have done an investigations in debug mode, and with lots of printf's. This is what I found:

> You could check that the key you're interested in is indeed registered here: https://github.com/SFML/SFML/blob/master/src/SFML/Window/OSX/HIDInputManager.mm#L272

The `HIDInputManager` constructor is called, it calls `initializeKeyboard`, which calls `loadKeyboard` twice, and each of these call `loadKey` many times. Loading fails for quite a few keys (`virtualCode` is 255), but my test key `Escape` (code 36) is loaded fine with both keyboards, and so are the other standard keys.

I am unsure why `loadKeyboard` is called twice, and whether this is good, bad, or neural. The keys of the "keyboards" are very similar, up to a few deviations in the end. I have only one physical keyboard, the built-in Mac keyboard. I do have, however, a non-standard keyboard layout selected in the preferences. I assume that the function is called once for each accessible layout. In case it matters, I have Karabiner-Elements running. @niklaskorz, do you have a standard configuration?

> Check also that the program enters [this loop](https://github.com/SFML/SFML/blob/master/src/SFML/Window/OSX/HIDInputManager.mm#L367).

It does, but it always returns `false`, even if the key is pressed.

**Comment by niklaskorz** [comment] 2017-07-15 22:56
@TGlas I'm indeed also using Karabiner elements on Sierra.

**Comment by soxfox** [comment] 2017-07-15 23:07
@TGlas I have found exactly the same thing, and I have the standard keyboard layout selected, with two others available for me to select. I also use karabiner-elements, and I will try using sfml without that running.

**Comment by niklaskorz** [comment] 2017-07-16 08:30
Ok, so I disabled Karabiner Elements, and indeed the key presses are detected in `sf::Keyboard`. My guess would be that although SFML does register for the physical keyboards, it does not register keypresses of virtual keyboards (e.g., Karabiner Elements).

**Comment by TGlas** [comment] 2017-07-16 09:34
@niklaskorz Thanks for the test, I can fully confirm this for my system. Closing Karabiner solves the problem, i.e., `HIDInputManager::isPressed` now returns true where appropriate.

I cannot see any difference in behavior during "loading" the keyboard, i.e., still two calls to `loadKeyboard`, the exact same calls to `loadKey` with the exact same results: same values for `key`, `code`, `usageCode`, and `virtualCode`. The exact same keys fail to load with and without Karabiner.

I vote for opening this issue again, since we have a rather clearly identified bug and hopefully a route to reproducing and solving the problem.

**Comment by soxfox** [comment] 2017-07-16 09:42
I think perhaps we should open a new issue specifically about Karabiner-Elements compatibility. This issue was created without a known cause, and now we know what app causes the problem.

**Comment by mantognini** [comment] 2017-07-16 09:46
Depending on the required workaround, SFML could implement it. But if it's too complex, I'd rather see a fix in Karabiner itself -- if it's possible to fix it, ofc.

What would be interesting is to see whether #1235 change in any way the current behaviour.

@soxfox I'm fine if we use this one to focus on this particular scenario.

**Comment by niklaskorz** [comment] 2017-07-16 09:49
Ok, so this is definitely related to *all* virtual keyboards. The same issue does not only apply to Karabiner Elements, but to macOS' screen keyboard as well.

![macOS virtual keyboard](http://i.imgur.com/5mfR4Zd.png)

While key presses of the screen keyboard are detected in the event loop, they are reported as not pressed in `sf::Keyboard::isKeyPressed`.

**Comment by TGlas** [comment] 2017-07-16 10:11
The discussion in [this Karabiner issue](https://github.com/tekezo/Karabiner-Elements/issues/155) may be helpful.

**Comment by stheno** [comment] 2017-12-17 20:33
I ran across this issue and found this in my search for answers.
I have been using NoMachine to use my mac and PC on the same screen/inputs.
Due to seeing this issue post I tried the Mac's plugged in keyboard. I concur that the virtual keyboard is the issue. Saved me hours if not days of hair pulling finding this issue post.
My program is not reliant on virtual keyboards for it's final release so it does not effect me really in "production".

**Comment by RiseAndCry** [comment] 2018-02-25 09:09
Thanks a lot guys, you saved me quite a lot of time :)

**Comment by naezith** [comment] 2018-03-10 17:32
One of my players is having this exact issue with High Sierra, Early 2014 Macbook Air.

The weird part is, he says there is no programs installed about keyboards. Should I open another issue about it or is this one related to his issue?

**Comment by stheno** [comment] 2018-03-10 18:19
@naezith If it is a software keyboard it is likely related from what I experience.

**Comment by naezith** [comment] 2018-03-10 19:37
@stheno He is using the laptop's own keyboard and no additional programs about keyboard.

**Comment by mantognini** [comment] 2018-03-14 20:21
If he is using a legit computer and no custom keyboard app/config, then it should work out of the box. But without more information, I can't help and can't investigate as I cannot reproduce this. I you guys are able to figure out a workaround, we can't discuss more about it.

**Comment by eXpl0it3r** [comment] 2024-09-24 12:07
Closing this, as this seems to be related to the changes Apple did regarding certain functionalities requiring Input Monitoring permissions. I've added a item to update the documentation.

Anyone stumbling up on this issue:
- Go to your System Settings
- Navigate to "Privacy & Security"
- Then "Input Monitoring"
- Add your application of IDE

![image](https://github.com/user-attachments/assets/bc538706-681a-4182-8ab2-51edf20ce2e8)

**Closed by eXpl0it3r** 2024-09-24 12:07 UTC
Labels: bug, m:sfml-window, p:macos
