### ISSUE TITLE
Wow

### ISSUE THREAD

**Issue by LaurentDuroisin** [SFML/SFML#1556] opened 2019-02-11 23:28 UTC
And you removed my issue now, wow, good!
Do you know what ? I'll try to set my framework without SFML because I see SFML is not a serious projet.

**Comment by binary1248** [comment] 2019-02-11 23:58
1. The issue was closed with a corresponding reason. This did not prevent you from commenting on why you think it should have been re-opened.
2. You did not provide any information that would help anybody else in resolving the problem, if it was even caused by SFML.
3. You disregarded the very text in the issue template that suggested asking on the forum first about any issues with the usage of SFML before opening an issue, which we prefer only contain confirmed bugs with appropriate information.
4. The issue was not removed. Please familiarize yourself with the way GitHub works before making such claims.
5. Threatening people in any way is not constructive and will not benefit anyone in any way.
6. You are entitled to believe what you want to believe, but making blanket statements such as "SFML is not a serious project" on an open platform has a high chance to mislead people into believing it as a fact. As such, in the future please refrain from making such remarks.
7. I have temporarily blocked you from the SFML organization for 7 days. Please take this time to calm down and reflect on what has just happened.
8. If you have any comments regarding the handling of this issue, please either take it to the forum or contact the SFML team via other means.
9. If, after you are unblocked, you intend to continue to post clearly non-constructive content, you will be permanently blocked from the SFML organization. This is your last warning.

Have a pleasant day.

**Closed by binary1248** 2019-02-11 23:58 UTC
