### ISSUE TITLE
CMake does not detect when 'libfreetype6-dev' is not installed, leading to build failure

### ISSUE THREAD

**Issue by Turbine1991** [SFML/SFML#1306] opened 2017-10-17 14:38 UTC
As the title describes, CMake happily builds the makefile without ensuring 'libfreetype6-dev' is available.

The build error:
`[ 42%] Building CXX object src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/Font.cpp.o
/home/turbine/src/SFML/src/SFML/Graphics/Font.cpp:35:10: fatal error: ft2build.h: No such file or directory
 #include <ft2build.h>
          ^~~~~~~~~~~~
compilation terminated.
src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/build.make:110: recipe for target 'src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/Font.cpp.o' failed
make[2]: *** [src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/Font.cpp.o] Error 1
CMakeFiles/Makefile2:281: recipe for target 'src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/all' failed
make[1]: *** [src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by MarioLiebisch** [comment] 2017-10-17 15:07
I'm not sure this is an actual bug in SFML. Could you look whether you actually have a `ft2build.h` somewhere on your system and which paths are detected by CMake?

I remember a similar (or the same?) bug being triggered if you've had an older version of FreeType installed before, which might have left some header files in the (now) wrong locations, so the CMake script finds the old path rather than the new one.

**Comment by Turbine1991** [comment] 2017-10-17 15:13
All I know is that it works once I install 'libfreetype6-dev', and it was the only dependency of which CMake didn't catch.

**Comment by eXpl0it3r** [comment] 2017-10-17 15:32
Can you expand your knowledge and see why CMake thinks freetype is installed?

Good starting point would be the (FindFreetype.cmake](https://github.com/SFML/SFML/blob/master/cmake/Modules/FindFreetype.cmake)

**Comment by MarioLiebisch** [comment] 2017-10-17 15:37
Just for reference, this might be a duplicate of #916.

**Comment by eXpl0it3r** [comment] 2018-01-25 11:01
Without further information or investigation, I'll close this for now.

If someone can provide more data points, we can reopen it.

**Closed by eXpl0it3r** 2018-01-25 11:01 UTC
Labels: m:sfml-graphics, p:linux, s:undecided
