### ISSUE TITLE
Unplugging gamepad crashes the game

### ISSUE THREAD

**Issue by naezith** [SFML/SFML#1198] opened 2017-03-04 10:31 UTC
I have two gamepad issues for months and finally wanted to create an issue about it.

I play my game with gamepad, then I unplug it, wait around 10 seconds and then I press a key on keyboard. Game crashes and debugger is pointing processEvents function inside the pollEvent->popEvent.

Here is what debugger shows at the crash moment:
https://puu.sh/utH6e/c8b0561b5e.png

Edit: Lag is fixed by the last joystick update. I also don't get the crash anymore but one player still gets the crash.

------

SFML 2.4.2
gcc (x86_64-posix-seh-rev1, Built by MinGW-W64 project) 6.3.0

**Comment by MarioLiebisch** [comment] 2017-03-04 10:36
It's caused by (or in combination with) the Steam Overlay. You always have to check the top of your call stack first:
![image](https://cloud.githubusercontent.com/assets/1854245/23578078/9c9ceefc-00ce-11e7-9134-b9343cc62679.png)

This might be hard to track down (and doesn't necessarily have to happen due to something SFML does).

As for lag/freezing, this might be related to #1179 and might be fixed with #1195, but it could be something different.

**Comment by naezith** [comment] 2017-03-04 11:01
It should not be about Steam because I started using Steamworks API this month, I had these issues for a long time.

**Comment by MarioLiebisch** [comment] 2017-03-04 11:02
Then try getting a stack trace without Steam showing up in the middle. Maybe it's related but has a different origin. Any chance you're polling events outside the main thread or anything similar?

**Comment by naezith** [comment] 2017-03-04 11:04
I will try to take the Steam out from there. Event polling runs on the main thread.

**Comment by naezith** [comment] 2017-03-04 12:10
Updated SFML, joystick update fixed it.

**Comment by naezith** [comment] 2017-07-14 08:45
A player reported today that it still crashes on unplug.
 
Also I found this on internet if it helps: 
https://twitter.com/hartlabs/status/631934662378590210

**Comment by eXpl0it3r** [comment] 2017-07-14 09:07
This must be a different issue then, so please open another issue. The one originally reported here has been fixed.

**Closed by eXpl0it3r** 2017-07-14 09:07 UTC
Labels: bug, p:windows, s:superseded
