### ISSUE TITLE
Regression: MacOS fullscreen mode 2.6.1 -> 2.6.2

### ISSUE THREAD

**Issue by md81544** [SFML/SFML#3330] opened 2024-11-28 11:08 UTC
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I am here to report an issue and not to just ask a question or look for help (use the [forum](https://en.sfml-dev.org/forums/index.php#c3) or [Discord](https://discord.gg/nr4X7Fh) instead)

### Describe your issue here

On ARM64 MacOS, 2.6.1 worked as expected in full screen mode. In 2.6.2, when I enter full screen mode, there is a black border around the writeable area.

### Your Environment

- OS / distro / window manager: MacOS Sequoia
- SFML version: 2.6.1 and 2.6.2
- Compiler / toolchain: clang++
- Special compiler / CMake flags: standard cmake build

### Steps to reproduce

I built the following small app against both 2.6.1 and 2.6.2

```cpp
#include <SFML/Graphics.hpp>
#include <SFML/Window.hpp>

#include <filesystem>
#include <iostream>
#include <vector>

int main(int, char* argv[])
{
    // Get the location of the executable (this will follow symlinks)
    std::filesystem::path executable(argv[0]);
    std::filesystem::path cwd = executable.remove_filename();

    std::vector<sf::VideoMode> modes = sf::VideoMode::getFullscreenModes();
    if (modes.empty()) {
        std::cout << "Empty set of modes returned\n";
    } else {
        for (std::size_t i = 0; i < modes.size(); ++i) {
            sf::VideoMode mode = modes[i];
            std::cout << "Mode #" << i << ": " << mode.width << "x" << mode.height << " - "
                      << mode.bitsPerPixel << " bpp" << std::endl;
        }
    }

    sf::RenderWindow window;
    if (!modes.empty()) {
        window.create(
            sf::VideoMode(modes[0].width, modes[0].height), "Test", sf::Style::Fullscreen);
    } else {
        // So we fall back to windowed. Any attempt at fullscreen will cause a segfault
        // owing to the bug outlined in my report at https://github.com/SFML/SFML/issues/2300
        window.create(sf::VideoMode(1280, 800), "Test");
    }
    window.setFramerateLimit(24);

    sf::Font font;
    std::filesystem::path fontFile = cwd / "open_sans.ttf";
    if (!font.loadFromFile(fontFile.c_str())) {
        std::cout << "Couldn't load font file " << fontFile.c_str() << std::endl;
        return 2;
    }
    sf::Text txt;
    txt.setFont(font);
    txt.setFillColor({ 0, 200, 0 });
    txt.setCharacterSize(100);
    std::string txtString = "Resolution: " + std::to_string(window.getSize().x) + " x "
        + std::to_string(window.getSize().y) + "\n\n" + "Press Esc to quit";
    txt.setString(txtString);
    txt.setPosition({ 100.f, 100.f });

    sf::RectangleShape rect;
    rect.setOutlineColor(sf::Color::Yellow);
    rect.setOutlineThickness(4.f);
    rect.setSize({ 1900.f, 1180.f });
    rect.setFillColor(sf::Color::Transparent);
    rect.setPosition({ 10.f, 10.f });

    while (window.isOpen()) {
        sf::Event event;
        while (window.pollEvent(event)) {
            if (event.type == sf::Event::Closed) {
                window.close();
            }
            if (event.type == sf::Event::KeyPressed) {
                if (event.key.code == sf::Keyboard::Escape) {
                    window.close();
                }
            }
        }
        window.clear({ 0, 0, 0 });
        window.draw(rect);
        window.draw(txt);
        window.display();
    }
}
```

Quick Makefile:
```
t: main.cpp
		clang++ -g -Wall -Wextra -Werror -Wpedantic -std=c++17 -o t main.cpp -L. -l sfml-graphics -l sfml-window -l sfml-system

```

### Expected behavior

There should be no difference in the display between 2.6.1 and 2.6.2

### Actual behavior

Black border around full screen app in 2.6.2

<img width="2056" alt="Screenshot 2024-11-28 at 11 06 37" src="https://github.com/user-attachments/assets/b84c82a3-d909-41ea-9b41-e5131e8b8197">

This is what it looks like under 2.6.1

<img width="2056" alt="Screenshot 2024-11-28 at 11 07 24" src="https://github.com/user-attachments/assets/5088511c-bf9c-4ded-9bbc-d632e1061d02">

**Comment by eXpl0it3r** [comment] 2024-11-28 13:06
I assume you're not setting anything specifically in the plist file, right? Just compile and run?

**Comment by md81544** [comment] 2024-11-28 13:10
Yes, just compile and run after `export DYLD_LIBRARY_PATH=.` to pick up the local libs.

**Comment by md81544** [comment] 2024-11-28 13:48
One other thing to add... the native resolution of my display (it's an M4 MB pro) is 3456x2234. I have mine set to 2056x1329 (the dimensions you see in the second screenshot). In the list of resolutions selectable, MacOS reports 1728x1117 as the default. Interesting that the first screenshot shows that as the screen size.

**Comment by Lorenzooone** [comment] 2024-11-28 16:57
It looks like your code still accounts for 2.6.1 (and earlier) issues.
Instead of:
`window.create(
            sf::VideoMode(modes[0].width, modes[0].height), "Test", sf::Style::Fullscreen);
    }`
try using:
`window.create(
            sf::getDesktopMode(), "Test", sf::Style::Fullscreen);
    }`

**Comment by md81544** [comment] 2024-11-28 17:08
Thanks for the suggestion, but I get the same result.

Incidentally, the stdout from the two runs show a difference in reported video modes.
2.6.1 reports just one available, the one I want:

```
Mode #0: 3840x2400 - 32 bpp
```

whereas the 2.6.2 version reports:

```
Mode #0: 1728x1117 - 32 bpp
Mode #1: 1728x1080 - 32 bpp
Mode #2: 1496x967 - 32 bpp
Mode #3: 1496x935 - 32 bpp
Mode #4: 1312x848 - 32 bpp
Mode #5: 1312x820 - 32 bpp
Mode #6: 1280x800 - 32 bpp
Mode #7: 1168x755 - 32 bpp
Mode #8: 1168x730 - 32 bpp
Mode #9: 960x600 - 32 bpp
```

... none of which match the full resolution of the screen.

**Comment by Lorenzooone** [comment] 2024-11-28 17:13
What does getDesktopMode report?

**Comment by md81544** [comment] 2024-11-28 17:18
```cpp
        auto dm = sf::VideoMode::getDesktopMode();
        std::cout << "DM Width: " << dm.width << ", Height: " << dm.height
                  << ", bpp: " << dm.bitsPerPixel
                  << ", valid = " << (dm.isValid() ? "true" : "false") << "\n";
        window.create(sf::VideoMode::getDesktopMode(), "Test", sf::Style::Fullscreen);
```

gives

```
DM Width: 2056, Height: 1329, bpp: 32, valid = false
The requested video mode is not available, switching to a valid mode
```

**Comment by md81544** [comment] 2024-11-28 17:39
Yes, using that branch stdout gives

```
Mode #0: 2056x1329 - 32 bpp
Mode #1: 1728x1117 - 32 bpp
Mode #2: 1728x1080 - 32 bpp
Mode #3: 1496x967 - 32 bpp
Mode #4: 1496x935 - 32 bpp
Mode #5: 1312x848 - 32 bpp
Mode #6: 1312x820 - 32 bpp
Mode #7: 1280x800 - 32 bpp
Mode #8: 1168x755 - 32 bpp
Mode #9: 1168x730 - 32 bpp
Mode #10: 960x600 - 32 bpp
```

and the fullscreen window displays as per the 2.6.1 screenshot in the original comment above.

**Comment by Lorenzooone** [comment] 2024-11-28 17:42
But yeah... 2.6.1 wasn't reporting the right resolution either. It was just reporting a giant resolution, in which the window fitted.
Going to make a PR.

**Comment by ChrisThrasher** [comment] 2024-12-08 22:24
> One other thing to add... the native resolution of my display (it's an M4 MB pro) is 3456x2234. I have mine set to 2056x1329 (the dimensions you see in the second screenshot). In the list of resolutions selectable, MacOS reports 1728x1117 as the default. Interesting that the first screenshot shows that as the screen size.

I have a MacBook Pro with, I believe, the same resolution display. I tried setting it to 2056x1329 just like you but when I run your example project it reports a resolution of 1728x1117. I would like to reproduce what you're seeing but something isn't quite lining up for me.

**Comment by md81544** [comment] 2024-12-09 07:04
> > One other thing to add... the native resolution of my display (it's an M4 MB pro) is 3456x2234. I have mine set to 2056x1329 (the dimensions you see in the second screenshot). In the list of resolutions selectable, MacOS reports 1728x1117 as the default. Interesting that the first screenshot shows that as the screen size.
> 
> I have a M1 MacBook Pro with, I believe, the same resolution display. I tried setting it to 2056x1329 just like you but when I run your example project it reports a resolution of 1728x1117. I would like to reproduce what you're seeing but something isn't quite lining up for me.

That sounds like what I'm seeing - 2.6.1 reports 2056x1329 as per the second screenshot above, whereas 2.6.2 gives the incorrect 1728x1117 (first screenshot), with the black border.

**Comment by ChrisThrasher** [comment] 2024-12-09 23:16
Oh right, I just realized I was testing with `2.6.x` and not `2.6.1`. When I switch to `2.6.1` I can reproduce your initial issue.

**Comment by ChrisThrasher** [comment] 2024-12-13 00:30
Resolved by https://github.com/SFML/SFML/pull/3331

**Closed by ChrisThrasher** 2024-12-13 00:30 UTC
Labels: bug, m:sfml-window, p:macos
