### ISSUE TITLE
error in the SoundFileWriterWav :: close () method

### ISSUE THREAD

**Issue by KrystianPotrykus** [SFML/SFML#1280] opened 2017-09-08 17:28 UTC
Hi,
I found an error in the SoundFileWriterWav :: close () method. 
Uint32 dataChunkSize = static_cast<Uint32>(m_sampleCount * m_channelCount * 2);  <------ bug
This variable (m_sampleCount) should not be multiplied by m_channelCount.
m_sampleCount contains the number of samples saved rather than the number of samples per channel. When I write a stereo wav 44100 samplerate this wav header has an invalid length of chunks.

To fix this:
Uint32 dataChunkSize = static_cast<Uint32>(m_sampleCount * 2);  <------ bug fix

```c++
void SoundFileWriterWav::close()
{
  // If the file is open, finalize the header and close it
  if (m_file.is_open())
  {
    m_file.flush();

    //Update the main chunk size and data sub-chunk size
    //Uint32 dataChunkSize = static_cast<Uint32>(m_sampleCount * m_channelCount * 2); <------bug
    Uint32 dataChunkSize = static_cast<Uint32>(m_sampleCount * 2);  //<------ bug fix
    Uint32 mainChunkSize = dataChunkSize + 36;
    m_file.seekp(4);
    encode(m_file, mainChunkSize);
    m_file.seekp(40);
    encode(m_file, dataChunkSize);
    m_file.close();
  }
}

```

**Comment by eXpl0it3r** [comment] 2017-09-08 21:32
I tried to find a specification that tells how it needs to be saved, but I'm also not sure exactly what block the close() function should be writing. Can you provide more information on that?

**Comment by LaurentGomila** [comment] 2017-09-09 08:27
The close function updates the "size" fields of the data chunk and the main chunk.

**Comment by eXpl0it3r** [comment] 2017-09-09 13:03
Still can't match "data chunk" and "main chunk" to any of the specifications I found. Maybe someone else needs to look at this.

**Comment by MarioLiebisch** [comment] 2017-09-09 13:37
It's just named in a potential misleading way.

A RIFF chunk has always three parts:

* 4 characters identifier (in our case: "RIFF", "fmt ", and "data".
* 4 bytes telling the remaining bytes in this chunk after.
* The actual data.

When closing only the offsets have to be updated:

* Offset 4 is the `mainChunkSize`, which is basically our root node and its size (file size minus 8 bytes previous header). The remaining nodes are children, therefore it's named "main" I guess.
* Offset 40 is the `dataChunkSize`, which should always be file size minus 44 bytes (together with the 8 bytes offset for `mainChunkSize` this explains SFML's magic number `36`).

The calculation used is certainly correct. The sample count is per channel and has to be multiplied with the number of channels. There might be a problem somewhere else; I haven't tested this yet, but if you have a sample rate of 44100, then you'll need 44,100 samples **per channel per second**; **not** 44,100 samples per second total.

**Comment by MarioLiebisch** [comment] 2017-09-09 14:12
Okay, just had to look this up, because it felt odd.

The problem is not in writing the header, but determining `m_sampleCount`, because it's misleading with multi-channel files.

Whenever a sample is written, `m_sampleCount` is increased by 1. However, this happens when both a sample is written for the left and the right (or any other channel).

This causes the weird discrepancy reported above. In the case of a stereo file, we're incrementing `m_sampleCount` twice as often due to having two channels.

I guess the easiest solution would be to just read the file size and calculate the offsets based on that, considering we're only supporting one sub format anyway.

**Closed** 2017-10-12 18:02 UTC
Labels: bug, m:sfml-audio, s:accepted
