### ISSUE TITLE
Unintuitive behavior of sf::Music::~sf::Music()

### ISSUE THREAD

**Issue by sim642** [SFML/SFML#891] opened 2015-05-21 13:20 UTC
I was recently confronted about a problem regarding use of SFML's audio module in the form of [this code](https://github.com/svkampen/Sonance/blob/11f458d9777890b914807bb70f9d698dfddee7c7/src/sonance.cpp) which inevitably crashes at the end of main. @svkampen's rigorous debugging has revealed that the problem lies in sf::Music's destructor.

What happens there is that sf::Music destructs also calling its sf::SoundStream destructor which wants stop the stream which in itself wants to seek to the beginning of the given sf::InputStream. Why the linked code crashes lies exactly in this behavior as the custom sf::InputStream gets destroyed before the sf::Music, causing problems at the last moment.

One might easily be led into thinking that **SFML is just being used wrong** in that scenario, sure but there's a catch. Consider other SFML classes which have similar layout: sf::Sprite loading sf::Texture, sf::Text loading sf::Font, etc. They all work and destruct perfectly fine regardless of the order they are introduced as they don't require the underlying resource to exist and be manipulatable at the point of their own destruction. This results in extremely confusing behavior where one class (sf::Music) has different requirements.

For this very reason of uniformity I think sf::Music **should not** manipulate the underlying stream at the point of destruction because logically it's completely unnecessary. When getting destroyed it does not matter at all what happens to the stream as it's not gonna manipulate it any further anyway. sf::Music should only care about cleaning up the audio things and the stream should care about cleaning up itself, not sf::Music.

At its current behavior sf::Music acts in this hybrid state of owning the stream and not owning it as well. From its use it seems like it wouldn't want ownership of the stream but from its destructor behavior it seems like it would like to have ownership of the stream object and control what happens to it. In my opinion this is **very unintuitive and hard to catch** for even for programmers with plenty of experience.

**Comment by eXpl0it3r** [comment] 2015-05-21 13:42
Just to put it out there: The problem with the code is that the stream gets destroyed before the sf::Music instance gets destroyed. The solution is to keep the stream alive as long as the sf::Music exists, i.e. put the stream deceleration before the sf::Music one.

The fact that sf::Sprite, sf::Text, etc. act so gracefully is in my opinion more a side-effect than a feature. When you pass a "reference" to an object you better make sure the referenced object lives longer than the object that received the reference. That's pure C++.

> At its current behavior sf::Music acts in this hybrid state of owning the stream and not owning it as well. 

That's not true. `sf::Music` doesn't own the stream in any kind of way. As said above you pass a reference which eventually comes with the contract/promise: "I will not delete this as long as you use it" and by destroying the stream before the music instance, you as a developer essentially break that promise and thus run into a crash.

> In my opinion this is very unintuitive and hard to catch for even for programmers with plenty of experience.

We might be able to add more info to the documentation if you think that's helpful, but honestly it's not that hard to catch if you properly think about the lifetime of your objects.

However I do have to agree that it might be handled problematically, since it might be very common in a larger project to have multiple sf::Music objects that get reused with different streams etc. and these streams then usually get created after the sf::Music objects. As such I see a problem where one can't "unload" the stream explicitly or rely on the `sf::Music` object not to crash.

Thanks for bringing it up and it would be interesting to hear other's thoughts on this.

**Comment by Bromeon** [comment] 2015-05-21 14:23
The `sf::Music` and `sf::Font` classes need access to their underlying resources as long as they live. This is outlined in the tutorial and the API documentation, so I wouldn't say the behavior is surprising.

As such, this is in no way specific to streams -- the same happens to files if you call `sf::Music::openFromFile()` and to memory buffers if you call `sf::Music::openFromMemory()`. I don't see the need to adapt something apart from possibly extending the documentation.

By the way: if you think you found a bug, please follow the [instructions in the contribution guidelines](http://www.sfml-dev.org/contribute.php#contributing). Most important: **create a thread in the forum before opening issues**. This tracker is for confirmed bugs and issues, we'd like to keep the tracker clean to keep a good overview. Thank you! :)

**Comment by MarioLiebisch** [comment] 2015-05-21 16:15
Maybe `sf::Music` should be renamed to `sf::StreamedSound` or something simila in SFML 3 to make it more clear that loading isn't "fire & forget"?

**Comment by Bromeon** [comment] 2015-05-21 18:29
Isn't the fact that the method is called differently (`openFromXy()` instead of `loadFromXy()`) **plus** the note in the documentation **and** tutorial enough (while the latter two can even be extended)? I don't like making the API ugly for all the people who use `sf::Music` correctly, just to help those who don't read the documentation :wink:

**Comment by eXpl0it3r** [comment] 2015-05-21 20:39
I don't think that would solve much, only make the API more strange and cause even more confusion between `sf::Sound`, `sf::SoundBuffer`, `sf::SoundStream`, `sf::SoundSource`, etc.

**Comment by binary1248** [comment] 2015-05-22 12:41
From a technical perspective, the behaviour of `sf::Music`'s destructor can't be changed without completely breaking behaviour anyway. It has to call `stop()` in order to stop the thread that is in charge of streaming samples, and `stop()` additionally resets the streams position to the start, as stated both in `sf::Music`'s and `sf::SoundStream`'s documentation. This can be useful if you want to reuse the stream in another Music/SoundStream after the first one was destroyed, which already implies that the stream has a longer lifetime than the Music that uses it.

I don't think the order of construction/destruction can be considered "unintuitive". If you explain the functionality of `sf::InputStream` as a data producer and `sf::Music` as a data consumer, it becomes obvious that the producer should outlive the consumer in order to guarantee behaviour. This isn't specific just to SFML data structures, and can be found elsewhere as well.

It is also generally recommended to destroy objects in the opposite order in which they were created/used. C++ does this automatically for all non-static objects, but since it can't infer the relationship between the objects you create in a specific order, you will have to make sure to sort them accordingly. As such, the example code you linked is simply broken, and it can be fixed easily just by moving the construction of the `sf::Music` object after the construction of the `SFTPInputStream` object (assuming of course that `SFTPInputStream` itself doesn't rely on `sftp` or `ssh`, which would be additional problems to fix).

With shared ownership semantics becoming more of a thing in C++11, this becomes less of a problem, but SFML doesn't make use of C++11 yet. I could imagine changes being made in SFML 3 that allows users to "allocate and forget", no longer having to deal with either this, the "white square problem" or other similar problems. All of that however, is not really the subject of this discussion and can be rolled into a larger overall discussion on usability enhancements for SFML 3. As such, I don't see much reason to keep this issue open any longer.

**Comment by svkampen** [comment] 2015-05-22 14:43
I don't agree with @MarioLiebisch's idea of renaming `sf::Music`, as the documentation makes it very clear that it streams data (which is exactly what I am, in fact, using it for). This was a user error (albeit one that could be solved by, for example, passing a stream to the constructor of sf::Music, or having a static method that creates a Music object for a stream - although that probably doesn't align with the general style within SFML). However, I do think these lines in the documentation are misleading:
>Since the music is not loaded completely but rather streamed continuously, the stream must remain alive as long as the music is playing (ie. you can't destroy it right after calling this function).  

([the sf::Music::openFromStream documentation](http://www.sfml-dev.org/documentation/2.0/classsf_1_1Music.php#a4e55d1910a26858b44778c26b237d673))  

>It also helps to keep in mind that the audio file has to remain available as long as it is played.

([the sf::Music and sf::Sound tutorial](http://www.sfml-dev.org/tutorials/2.1/audio-sounds.php))

These lines imply that the stream need only be alive while the Music instance is being played; i.e. the stream can be destructed after the Music instance has stopped playing. They say nothing about whether the stream needs to be alive when the Music instance is being destructed.

Additionally, I don't see why the file has to be rewound when the Music instance is being destructed. I understand that this is a side effect from calling `stop()`, which also stops the thread used by the instance. However, when the instance is being destructed, one will not `play()` it again, and the normal behavior of rewinding the stream when an instance is stopped is unnecessary.

**Comment by MarioLiebisch** [comment] 2015-05-22 14:52
> Isn't the fact that the method is called differently (openFromXy() instead of loadFromXy()) **plus** the note in the documentation **and** tutorial enough (while the latter two can even be extended)?

Auto-complete makes looking up stuff often unnecessary or seem arbitrary. :)

But yeah, I agree that it could make the other differentiation harder, i.e. the whole buffer vs. sound thing.

**Comment by binary1248** [comment] 2015-05-22 15:20
> Additionally, I don't see why the file has to be rewound when the Music instance is being destructed. I understand that this is a side effect from calling stop(), which also stops the thread used by the instance. However, when the instance is being destructed, one will not play() it again, and the normal behavior of rewinding the stream when an instance is stopped is unnecessary.

Like I said... other objects might want to use the stream even after the `sf::Music` is done with it. The stream isn't always destroyed with the `sf::Music` if that is what you think happens.

`sf::Music` basically resets the stream into its original state in which it was right after it was constructed. This is what is understood when "stopping" the stream as opposed to merely "pausing" the stream, which doesn't reset the position.

If this (stopping) was not done, attaching the stream to something else after detaching from the first one could (doesn't if the new object rewinds but this is not guaranteed) start playing where the first one left off. Either scenario can be considered a "feature", but SFML decided for the first (reset on detach) one, since it is probably the more useful one and is easier to explain/document.

**Comment by eXpl0it3r** [comment] 2015-05-23 09:41
So any suggestions on how to change the text in the documentation?

**Comment by Bromeon** [comment] 2015-05-23 13:18
Yes, [here](https://github.com/SFML/SFML/pull/894) :)

As we agree that the implementation needn't be adapted because of wrong usage, I'll close this issue.

**Closed by Bromeon** 2015-05-23 13:18 UTC
Labels: bug, m:sfml-audio, s:undecided
