### ISSUE TITLE
A suggested fix for errors when running examples and it says cannot find shared object file

### ISSUE THREAD

**Issue by cbalen** [SFML/SFML#990] opened 2015-10-18 19:53 UTC
So I know this has been reported before and the issue was closed (https://github.com/SFML/SFML/issues/752), where the response was to use ldconfig. I have had this issue with other software and have used a different solution to solve the problem when you are installing SFML so people don't have to go searching for the error and then use ldconfig. This CMake page discusses the issue (http://www.cmake.org/Wiki/CMake_RPATH_handling) and I've found that if you follow their recommendation (section Always full RPATH) then it resolves the issue. I added the code (shown below) between lines 9-11 of your SFML-2.3.2/CMakeLists.txt file then you don't have this problem. I'm using OpenSUSE 13.1, and after adding this code it seems to have been resolved and I can now run the examples/window executable without having to touch ldconfig. I mentioned this in the other thread but no one responded and I wasn't sure if it was because it was closed so the other people don't see any further responses. Anyways, I thought I would mention it again in case you're interested in including it in the future.

CMake Code:
SET(CMAKE_SKIP_BUILD_RPATH FALSE)
SET(CMAKE_BUILD_WITH_INSTALL_RPATH FALSE)
SET(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")
SET(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)

LIST(FIND CMAKE_PLATFORM_IMPLICIT_LINK_DIRECTORIES "${CMAKE_INSTALL_PREFIX}/lib" isSystemDir)
IF("${isSystemDir}" STREQUAL "-1")
SET(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")
ENDIF("${isSystemDir}" STREQUAL "-1")

**Comment by eXpl0it3r** [comment] 2015-10-19 06:49
Please refer to the [Contribution Guidelines](http://www.sfml-dev.org/contribute.php) for further reports. We try to keep this tracker to confirmed bugs and features only.

I'm not exactly sure how this works, what I do know is that [RPATH has been re-enabled](https://github.com/SFML/SFML/commit/e157e7a) and that we have an [open issue for OS X](https://github.com/SFML/SFML/issues/971).

**Comment by TankOs** [comment] 2015-10-19 07:42
You should be able to run the examples if you run them from the intermediate build directory, because `RPATH` is still available then. After installing, you have to run `ldconfig`.

Personally I don't think it's a good idea to add absolute and fixed `RPATH` values to either the executable or libraries. Copying .so files to `/usr/lib` (or any other related directory) and running `ldconfig` is just how it works. Though, normally your package manager of choice takes care of updating ld's cache after installing libraries.

**Comment by StevenChristy** [comment] 2015-10-25 16:30
I don't see how this is an issue with SFML. In my case I'd prefer to disable RPATH all together via cmake -DCMAKE_SKIP_RPATH=TRUE or when using cmake-gui you can add CMAKE_SKIP_RPATH to the list of values (it won't appear in the list) and set it to true. I don't think SFML should fiddle with RPATHs itself. This is a learning thing on the part of a Linux developer - once you learn how RPATHs work you should realize its your responsibility to configure it. CMAKE does all the heavy lifting and SFML should stay out of the way.

**Comment by eXpl0it3r** [comment] 2016-04-20 19:26
Is this still an issue? Are there any further comments? @cbalen, @TankOs, @StevenChristy 

Otherwise I'll close this.

**Comment by cbalen** [comment] 2016-04-23 16:41
No I don't think so, I just wanted to point out a method to change the CMake so you don't need to use ldconfig in case other people were interested.

**Comment by binary1248** [comment] 2016-08-01 16:01
This is a packaging issue more than a CMake/SFML one. Closing this.

**Closed by binary1248** 2016-08-01 16:01 UTC
Labels: feature, m:config, not an issue, p:linux
