### ISSUE TITLE
Why SFML needs X11 for RenderTexture?

### ISSUE THREAD

**Issue by cyber-loli** [SFML/SFML#1812] opened 2021-08-05 11:13 UTC
I want to use RenderTexture for creating image and save it to file, but when i try to do it without X11, i get error:
```
Failed to open X11 display; make sure the DISPLAY environment variable is set correctly
Aborted (core dumped)
```

My code:

```cpp
#include<SFML/Graphics.hpp>

using namespace sf;

int main()
{
	RenderTexture drawtex;
	drawtex.create(800, 600);
	
	CircleShape shape(100.f);
	shape.setFillColor(Color::Red);
	
	drawtex.clear();
	drawtex.draw(shape);
	drawtex.display();

	drawtex.getTexture().copyToImage().saveToFile("image.png");

}
```

PS. Sorry for my english.

**Comment by eXpl0it3r** [comment] 2021-08-05 12:21
SFML isn't built to run without X11. It doesn't "lazy load" X11 as active dependency, because there are global handlers required for all features of SFML. There are some [attempts being made](https://github.com/mickelson/sfml-pi) (and hopefully merged at one point) with making SFML work without X11.

For questions about SFML you should be using the [SFML forum](https://en.sfml-dev.org/forums/index.php#c3) or join our [Discord server](https://discord.gg/nr4X7Fh), as we try to keep the issue tracker for confirmed issues with SFML.

**Closed by eXpl0it3r** 2021-08-05 12:21 UTC
