### ISSUE TITLE
Remove `runtests` target

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2429] opened 2023-02-27 22:07 UTC
## Subject of the issue

The `runtests` target was added in #1475 without much fanfare. I tried to find any discussion about its rationale but didn't see any so I'm not sure what its proponents would say about it.

I propose we remove it for the following reasons:
1. It increases build times. No matter what, each build must run the tests. That means a no-op incremental build actually takes a few seconds since it has to run the tests even though no code has changed. As we add more tests, this build time penalty gets bigger and bigger. 
2. It's non-standard. I'm not aware any CMake project that does this. It's a bit surprising to have the tests get automatically run when all you did was ask CMake to build the project.
3. It does not produce color output. Running `ctest` will give you nicely colored output but the `runtests` target due to it using `add_custom_command` only produces a monochromatic output making it a bit harder to parse.
4. It's additional code to maintain. It's not particularly difficult to maintain, but it's a non-zero cost nonetheless.

Because our use of OpenCppCoverage on Windows ties into `runtests`, some work will be required to extract that code from the build scripts into the CI pipeline but I believe this is a solvable problem.

**Comment by kimci86** [comment] 2023-02-27 22:16
Another reason to remove it: running tests quickly opens and closes a few windows now that we have tests about that. I think it might be okay when explicitly running the tests but it seems surprising otherwise.

A simple solution at first is to remove `runtests` target from the default target, simply remove ALL from `add_custom_target` [here](https://github.com/SFML/SFML/blob/474de4d16e570b9cb4258d85d5f9142a26e22202/test/CMakeLists.txt#L142).

**Comment by ChrisThrasher** [comment] 2023-02-28 16:17
See https://github.com/SFML/SFML/pull/2430

**Comment by binary1248** [comment] 2023-03-11 01:58
After working on #2442 I have come to see why having a `runtests` target can be useful in many situations.

Regarding points 1. and 2.: That is just a matter of removing `runtests` from `ALL` like I did in #2442. Once that is done you will be able to manually control when to run tests yourself.

Regarding point 3.: ctest would only be able to produce colour output in consoles that support it. This assumes that the normal way developers would want to run tests is by having a separate console open to run tests in. This might be the case for people working in Unix environments, but I myself would personally find it awkward to have a console separate from my main IDE on e.g. Windows just to run tests in.

Not many IDEs have first-party (or even add-on) support for running tests using ctest. In these cases removing the `runtests` target is equivalent to forcing people to invoke ctest through out-of-IDE means or some in-IDE console. I can imagine that this can become quite annoying quite fast (because I am one of those people). In the current state with the `runtests` target, people can choose how they want to run ctest. If they want colour, great, separate console window. If they don't care about colour, just build the `runtests` target and check if it passes. Removing something in order to support a feature by giving users less freedom doesn't sound right to me.

Also, because the question was asked in #2430, I always refer to local coverage reports when writing tests. It helps to know if I am moving in the right direction without having to push after every incremental change. Although CI is practically free, we shouldn't take it for granted and push too gratuitously. The best way to reduce CI build times is by not pushing at all.

When profiling an executable, every bit helps to improve the expressiveness and precision of the coverage data. In order to do this, the compiler and linker have to be instructed to generate additional information that can be used after profiling is complete. See [here](https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html) and [here](https://clang.llvm.org/docs/UsersManual.html#gcov-based-profiling). This is why I added CMake support for generating coverage instrumentation. Moving this functionality out of CMake is not technically possible and removing it would lead to worse coverage data.

Moving testing and coverage functionality out of CMake and into ci.yml would have the effect that anybody who wants to run tests or compute coverage would have to do the legwork themselves for something that worked perfectly fine in the past (granted I support removing `runtests` from ALL since this makes sense). If at some point we wanted to compute coverage on BuildBot as well I would have to reproduce the ci.yml configuration there too.

The majority of the concerns in this issue can be addressed by the simple change of removing `runtests` from `ALL`. This is a change I can support, completely removing `runtests` would be a bit too extreme for me.

**Comment by ChrisThrasher** [comment] 2023-03-11 02:03
> Not many IDEs have first-party (or even add-on) support for running tests using ctest. In these cases removing the runtests target is equivalent to forcing people to invoke ctest through out-of-IDE means or some in-IDE console.

I don't think this is true. You can just as easy build the default `test` target as you can our custom `runtests` target. Nothing is more difficult about using Test and the `test` target than our bespoke recreation of that.

> Moving testing and coverage functionality out of CMake and into ci.yml would have the effect that anybody who wants to run tests or compute coverage would have to do the legwork themselves for something that worked perfectly fine in the past (granted I support removing runtests from ALL since this makes sense). 

This doesn't have to be true. We can easily define a CMake preset for code coverage that can be used locally and in CI. That makes it very simple to enable all the flags required to enable coverage without having to bake that into our build scripts.

**Comment by ChrisThrasher** [comment] 2023-03-11 02:21
I see your point now. The `runtests` target is not the problem. The problem I have is two fold. First is the fact that tests are automatically run. That is easily fixed by removing it from the `all` target. My second issue is the fact that we have code coverage stuff baked into the build scripts when it's better off being external to the build. 

We can keep the `runtests` target. I'll eventually get around to amending #2430 to keep that target around for you.

**Closed** 2023-03-15 02:23 UTC
Labels: feature, m:unittest
