### ISSUE TITLE
sf::Joystick::PovY is inverted on Linux

### ISSUE THREAD

**Issue by naezith** [SFML/SFML#1292] opened 2017-09-26 17:25 UTC
`sf::Joystick::PovY` is coming inverted compared to Windows. It is same for `sf::Event::JoystickMoveEvent` and `sf::Joystick::getAxisPosition(joystickId, sf::Joystick::PovY)`.

I press Up at D-pad, on Windows I get 100, on Linux I get -100.
Analog Stick (sf::Joystick::Y) works fine on the other hand.

I can write OS-dependent code and just invert the value but that would be the only OS-dependent code in my big project.

```cpp
#include <SFML/Graphics.hpp>
#include <iostream>

int main() {
    sf::RenderWindow window;
    window.create(sf::VideoMode::getDesktopMode(), "Inverted PovY", sf::Style::Default);

    while(window.isOpen()) {
        sf::Event event;
        while(window.pollEvent(event)) {
            if(event.type == sf::Event::Closed) window.close();
            else if(event.type == sf::Event::JoystickMoved && event.joystickMove.axis == sf::Joystick::PovY)
                std::cout << event.joystickMove.position << std::endl;
        }

        std::cout << sf::Joystick::getAxisPosition(0, sf::Joystick::PovY) << std::endl;

        window.clear(sf::Color::Red);
        window.display();
    }

    return 0;
}
```

**Logitech F310 Gamepad
Linux (Ubuntu 16.04), SFML 2.4.2**

**Comment by LaurentGomila** [comment] 2017-09-27 04:33
When you click the "New issue" button on github, there's a message inviting you to read the rules. And these rules clearly state that [bug reports should first be posted and discussed on the forum](https://www.sfml-dev.org/contribute.php#reporting-bugs).

So please follow the rules.

**Comment by RUSshy** [comment] 2017-09-27 08:12
This is stupid, why use git for SFML then?

**Comment by mantognini** [comment] 2017-09-27 08:21
There's a big difference between git and an issue tracker such as this one... We want to centralise discussions in one place, i.e. the forum, and that's why we have these contribution rules. We **will** reopen this **if** it's indeed a confirmed issue.

**Comment by LaurentGomila** [comment] 2017-09-27 08:33
These rules exist for a lot of very good reasons, and feel free to discuss them if you need to, but not on this tracker please 😉

**Comment by eXpl0it3r** [comment] 2017-09-28 22:30
Would be useful if you could debug this and see where the values comes from and what the driver reports on. It does sound suspicious that event and static function report different values.

**Comment by naezith** [comment] 2017-09-29 04:07
@eXpl0it3r they report same sign on same OS. They both are inverted together on Linux.

**Comment by eliasdaler** [comment] 2017-10-06 19:59
Not sure if it's a bug really. Both F310 and Xbox 360 controller have PovY-Down as +, PovY-Up as - on Linux. It's the other way around on Windows. 

I think that this behavior is not SFML bug. Drivers on Windows and Linux report the same values, so that's just probably how different systems treat game pad axes.

I'm not sure that this applies to all game pads, though, would be nice if someone tested this with other devices.

**Comment by mantognini** [comment] 2017-10-06 20:17
In any case, wouldn't anyone using joysticks need an invert axis option in
the user settings? I understand that it's puzzling to get different values
on different OSes, but is that really an issue?

**Comment by naezith** [comment] 2017-10-06 20:29
@mantognini It's just weird when they open the game and pressing up in menu goes down. Not a super big issue but yeah. 

@eliasdaler If it's inverted in every case, then it should be handled inside SFML imo because I don't want to code a `#ifdef __linux__` in my project, that does not look like SFML code.

**Comment by eliasdaler** [comment] 2018-02-22 09:02
Any further thoughts on this? I think it'll be nice to have unified coordinate system for D-pads on all platforms.

**Comment by MarioLiebisch** [comment] 2018-02-22 09:15
I don't have any Linux system in use currently (except a VM), so can't really test it under real conditions. But overall I agree, the alignment should be identical no matter the platform.

**Comment by eliasdaler** [comment] 2018-02-22 09:55
Hmm, it also looks like wireless controllers on Linux don't even support axes for d-pad... (looks like driver limitation) Can anyone with a wireless gamepad test it? (e.g. by using `jtest /dev/input/js0`).

And I have no idea how Mac treats D-pad axes by default. Can anyone test it too, please?

**Comment by MarioLiebisch** [comment] 2018-02-22 10:31
It's up to the driver how to interpret components. It's not really standardized either. It's certainly possible a dpad is handled as a coolie hat, single buttons, or similar, it doesn't have to represent axes.

**Comment by TheMaverickProgrammer** [comment] 2019-04-07 19:41
Can confirm the axis is inverted on Linux. Tried with Rock Candy (xbox) controller and Logitech F310. All other buttons seem to be A-OK.

**Comment by eliasdaler** [comment] 2019-04-08 08:24
Gamepads make no sense most of the time. 

https://github.com/gabomdq/SDL_GameControllerDB - check this out, gamepads on the same system can have axes inverted! 

I think that SFML shouldn't handle this - this is how a driver reports the values of axes, which map to real gamepads in very strange ways sometimes. 

The only real solution is to have gamepad "db" like SDL's. I already have a prototype for such library and I just don't have time to come back to it.

**Comment by TheMaverickProgrammer** [comment] 2019-04-08 10:41
@eliasdaler I'm familiar with the DB. If it's a driver issue I agree there should be an SFML DB for gamepads. Please share the repo so I can contribute a few gamepads as well.

**Comment by eXpl0it3r** [comment] 2023-01-23 09:27
As mentioned, SFML reports what the OS provides. The specific mapping of the provided OS values, might be something we'll add support for with a sort of controller DB at one point, if at all possible. For that we have #1950

As such, I'll close this issue.

**Closed by eXpl0it3r** 2023-01-23 09:27 UTC
Labels: bug, m:sfml-window, s:accepted, p:linux
