### ISSUE TITLE
GIF transparency broken on Windows / MSVC

### ISSUE THREAD

**Issue by CelticMinstrel** [SFML/SFML#978] opened 2015-09-28 22:58 UTC
In SFML 2.3, the transparency in GIF images does not appear to be correctly applied on Windows (using MSVC 12). This applies to 2.3.0, 2.3.1, and 2.3.2. It works correctly on the Mac in 2.3.2, and on Windows in 2.2.0; I didn't check any minor revisions of 2.2.

Possibly of note is that the GIF images in question contain GIF comments, but when I tried removing the comment it didn't change anything.

Test code:

```
#include <iostream>
#include <SFML/Graphics.hpp>

int main() {
	std::cout << "SFML Version: " << SFML_VERSION_MAJOR << '.' << SFML_VERSION_MINOR << '.' << SFML_VERSION_PATCH << std::endl;
	sf::RenderWindow win;
	win.create(sf::VideoMode(100,100), "Test", sf::Style::Titlebar | sf::Style::Close);
	sf::Texture boot;
	boot.loadFromFile("boot.gif");
	sf::Sprite sprite(boot);
	while(win.isOpen()) {
		sf::Event evt;
		if(win.pollEvent(evt) && evt.type == sf::Event::Closed)
			win.close();
		win.clear(sf::Color::Magenta);
		win.draw(sprite);
		win.display();
	}
	return 0;
}
```

Compiled with: `cl /EHsc test.cpp sfml-graphics.lib sfml-audio.lib sfml-window.lib`

The image boot.gif can be found [in my repo](https://raw.githubusercontent.com/calref/cboe/ff7f3cca4720da7fd4ebceb3b2fd2bcd3b86079c/rsrc/cursors/boot.gif).

When compiled against SFML 2.2, the above code produces the image shown against a magenta background, as expected. When compiled against SFML 2.3 and later, the image is shown in a white square.

**Comment by eXpl0it3r** [comment] 2015-09-29 00:15
As we have told you before the GitHub issue tracker is for confirmed bugs only. Please follow the [contribution guidelines](http://www.sfml-dev.org/contribute.php) and post on the forum first.

It seems to highly depend on the used GIF format, because using an image editor of mine I can create a working GIF.

![booty](http://my-gate.net/pub/sfml/random/booty.gif)

But yours (as well as others) don't work as expected. Not exactly sure why, but what I am sure of is that this has nothing to do with SFML directly, because we just use nothings' [stb_image header](https://github.com/nothings/stb/blob/master/stb_image.h) and we updated the version from 2.2 to 2.3. So feel free to report the issue over at nothings' repository, they might know more about what formats are properly supported.

**Comment by CelticMinstrel** [comment] 2015-09-29 03:21
I did look at the contribution guidelines but I guess I didn't read closely enough. I think that's actually quite a silly policy, but, well, it's your repo - if I encounter another issue I'll be sure to go to the forums.

By the way, it might be an idea to include stb via git submodule instead of directly importing the code into your repository.

(Should I close this issue, since I guess it's not really a SFML issue? It still does affect SFML, though, so maybe it should be kept open until you update stb again. I guess I'll leave it up to you.)

**Comment by Bromeon** [comment] 2015-09-29 05:10
> I think that's actually quite a silly policy, but, well, it's your repo

It lets us keep tasks organized, when not everybody with a question or a misunderstanding runs directly to the GitHub tracker.

> By the way, it might be an idea to include stb via git submodule instead of directly importing the code into your repository.

That makes it more difficult to choose the right version, requires one extra step for every user that clones/pulls the repo, and makes it impossible for us to modify STB, in case we need to adapt something specifically for SFML.

**Comment by CelticMinstrel** [comment] 2015-09-29 06:03
Fair enough, and the point about modifying it if necessary is quite valid (I've even done that with my copy of TinyXML).

**Comment by eXpl0it3r** [comment] 2015-09-29 06:12
> I guess it's not really a SFML issue? It still does affect SFML, though, so maybe it should be kept open until you update stb again.

Well first it needs to be determined whether it it is and how it is an issue. Just because something doesn't behave the way you expect, doesn't mean it's necessarily broken. In the meantime I'll close this issue and everyone having issues with it can just use a PNG instead.

**Closed by eXpl0it3r** 2015-09-29 06:12 UTC
