### ISSUE TITLE
Android sends Delete event instead of Backspace

### ISSUE THREAD

**Issue by texus** [SFML/SFML#1309] opened 2017-10-22 13:38 UTC
SFML maps the [AKEYCODE_DEL](https://developer.android.com/ndk/reference/group___input.html#gga39fca1837c5ce7715cbf571669660c13acd013221b457d98975dc47e49817e28a) event to Keyboard::Delete ([WindowImplAndroid.cpp#L623](https://github.com/SFML/SFML/blob/013d053277c980946bc7761a2a088f1cbb788f8c/src/SFML/Window/Android/WindowImplAndroid.cpp#L623)) while AKEYCODE_DEL is actually the backspace key. The real delete key is [AKEYCODE_FORWARD_DEL](https://developer.android.com/ndk/reference/group___input.html#gga39fca1837c5ce7715cbf571669660c13a9516bc190d37fea27e07ddab0c607b51).

It was mentioned before in [this forum post](https://en.sfml-dev.org/forums/index.php?topic=13716.msg105902#msg105902), but it seems like it has been overlooked.

**Comment by Foaly** [comment] 2018-01-29 19:24
@texus I could write a fix for this, but I have no way of testing it. Would you be able to test, if I write a PR?

**Comment by texus** [comment] 2018-01-29 21:04
The fix is pretty trivial (just change that line and add another case statement), so there isn't much that really has to be tested. But yeah, if you create PR then I will run it to verify that it works.

**Comment by Foaly** [comment] 2018-01-29 21:38
Awesome! Yeah test is maybe not the right wording in this trivial case. Maybe you can verify that it fixes the bug as intended. You can find the PR here #1362. If somebody from the team kicks the buildbot there will even be binarys.

**Comment by eXpl0it3r** [comment] 2018-02-15 20:23
Fixed with #1362 and merged in 186294607f32c4ec8fcb32104af8516bed63e1da

**Closed by eXpl0it3r** 2018-02-15 20:23 UTC
Labels: bug, m:sfml-window, p:android, s:accepted
