### ISSUE TITLE
2 dependency build issues on macOS, with workarounds

### ISSUE THREAD

**Issue by kurtisharms** [SFML/SFML#1191] opened 2017-02-12 08:08 UTC
The current cmake->make build process on mac has two dependency issues out-of-the-box.

**Issue 1: Freetype**
First, the module `FindFreetype.cmake` will find FreeType in the Mono framework if it is installed (a fairly common framework), which results in the following error:
```
[ 47%] Building CXX object src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/Font.cpp.o
In file included from /Users/kurtis/Programming/gameLib/SFML/src/SFML/Graphics/Font.cpp:35:
/Library/Frameworks/Mono.framework/Headers/ft2build.h:56:10: fatal error: 
      'freetype/config/ftheader.h' file not found
#include <freetype/config/ftheader.h>
         ^
1 error generated.
make[2]: *** [src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/Font.cpp.o] Error 1
make[1]: *** [src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/all] Error 2
make: *** [all] Error 2
```

A workaround is to remove the Mono framework from `/Library/Frameworks`, but ideally the `FindFreetype.cmake` module would be smarter about this.

**Issue 2: jpeglib header issue**
The file `jpeglib.h` included with SFML isn't being properly found.
```
[ 45%] Building CXX object src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/Font.cpp.o
[ 46%] Building CXX object src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/Glsl.cpp.o
[ 47%] Building CXX object src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/GLCheck.cpp.o
[ 48%] Building CXX object src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/GLExtensions.cpp.o
[ 48%] Building CXX object src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/Image.cpp.o
[ 49%] Building CXX object src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/ImageLoader.cpp.o
/Users/kurtis/Programming/gameLib/SFML/src/SFML/Graphics/ImageLoader.cpp:37:14: fatal error: 
      'jpeglib.h' file not found
    #include <jpeglib.h>
             ^
1 error generated.
make[2]: *** [src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/ImageLoader.cpp.o] Error 1
make[1]: *** [src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/all] Error 2
make: *** [all] Error 2
```

Workaround was to do a `brew install jpeg` and compilation proceeded smoothly from there! 

I see that in `SFML/extlibs/headers/jpeg/` there is `jpeglib.h`, but the default cmake->make scripts aren't properly finding this? Not sure why though. 

I am not a cmake / make expert, so I'm sorry for not being able to provide proper fixes for these issues!

**Comment by mantognini** [comment] 2017-02-14 15:17
> Issue 1: Freetype

Here the issue is more with Mono.framework than anything else: it should not publicly expose these headers. It should be reported to them actually.


> Issue 2: jpeglib header issue

> I see that in SFML/extlibs/headers/jpeg/ there is jpeglib.h, but the default cmake->make scripts aren't properly finding this? Not sure why though.

These scripts works fine here. Maybe you have some env variables doing something weird? What would be interesting is a debug log of your cmake run, after uninstalling jpeg from brew, and give us the cmake cache as well. Give us also the cmake version you're using an the other relevant programs' version you have.

---

As we try to keep this issue tracker for confirmed issues only we would appreciate if you could discuss future issues first on our forum. The procedure to open a bug/feature request is explained in [the contribution guidelines](http://www.sfml-dev.org/contribute.php). Thanks.

**Comment by mantognini** [comment] 2017-02-20 15:29
Closing this for now. If you still believe this is a SFML bug, then feel free to add more information to this discussion.

**Closed by mantognini** 2017-02-20 15:29 UTC
Labels: bug, m:sfml-graphics, p:osx, s:undecided
