### ISSUE TITLE
Gnome flags SFML windows unresponsive.

### ISSUE THREAD

**Issue by tapir** [SFML/SFML#1089] opened 2016-05-21 20:07 UTC
As discussed on the topic: http://en.sfml-dev.org/forums/index.php?topic=19715
There is a fix #947 that is not working for me. I'm on Arch Linux with Gnome 3.20 and tried the SFML/CSFML from the official repos along with compiling the latest git versions of both of them and the window is still flagged as unresponsive. It doesn't have to be fullscreen as suggested. It always happens.

@binary1248, After a quick chat with a "Clutter" developer on IRC, it's certain that this only happens if the application doesn't respond properly to _NET_WM_PING. I asked specifically if anything else can cause this and the answer was no. I don't know if that helps but that's the only information I got.

**Comment by tapir** [comment] 2016-05-23 17:45
Something I've noticed today is that when there is another opengl window (I'm playing Axiom Verge to be clear. It uses SDL2 through FNA monogame fork) I don't get this message. Go figure :)

**Comment by bsaleil** [comment] 2016-05-31 02:05
Hi,
Same bug here using Arch Linux with Gnome 3.20.
I don't know if it helps but I noticed that the window manager logs the following message to session logs:
`Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0xa0000c (SFML windo)`

**Comment by buchwj** [comment] 2016-06-03 14:52
Hello,
I've observed the same issue on Fedora 22 with Gnome 3.16 using the distro-provided SFML packages.  I also cloned this repository and built the latest version, but the same error appears.

**Comment by tapir** [comment] 2016-06-09 11:03
> Hi,
Same bug here using Arch Linux with Gnome 3.20.
I don't know if it helps (and if it's related) but I noticed that the window manager logs the following message to session logs:
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0xa0000c (SFML windo)

This is promising. Any news on this?

**Comment by SirSharpest** [comment] 2016-07-15 12:26
I can confirm I have the same issue on Ubuntu 16.04 with Gnome 3.18 

Another issue that I've had is once this is triggered any input via SFML is activated and will not stop. I.e. if I was moving a character to the right, when the unresponsive error appears then I would not be able to stop moving to the right.

**Comment by leestrippfilms** [comment] 2016-07-31 14:55
I have the same issue on Antergos running Gnome 3.20.2

Is this as simple as fixing the timeout length on the event?

**Comment by binary1248** [comment] 2016-08-14 02:11
Try out the [bugfix/xlib](https://github.com/SFML/SFML/tree/bugfix/xlib) branch and see if it fixes the problem.

**Comment by eXpl0it3r** [comment] 2016-08-18 17:42
@tapir, @SirSharpest, @bsaleil, @buchwj can you try the [bugfix/xlib](https://github.com/SFML/SFML/tree/bugfix/xlib) branch? CI snapshots can be found [here](http://www.sfml-dev.org/artifacts/by-branch/bugfix/xlib/).

**Comment by tapir** [comment] 2016-08-18 18:53
@eXpl0it3r for me it looks like its fixed. thank you

**Comment by bsaleil** [comment] 2016-08-18 21:47
Thanks for trying to fix that @binary1248.
Today I first tried to reproduce the bug using an updated system (Antergos) with latest SFML version (without using xlib branch).
Strange thing is that I'm not able to reproduce the bug using my laptop. I then switched to my desktop computer (still Antergos & Gnome) and I'm still not able to reproduce it.
The fact is that the bug was particularly hard to reproduce for me, so I don't really know if it's fixed or just not showing.

**Comment by SirSharpest** [comment] 2016-08-19 12:51
Yep that's sorted. 

What was the issue out of curiosity?

**Comment by tapir** [comment] 2016-08-19 12:53
From what I understand they completely switched from XCB to Xlib. I'm ok with it since XCB never lived up to its potential and it doesn't have to anymore since we will have Wayland in the near future.

**Comment by Ostefanini** [comment] 2016-09-15 08:39
Okay, so to fix it we have to use a special branch or just use 2.4 ? because in my school everyone use gnome and SFML and everyone have this issue (we are 500+)

**Comment by eXpl0it3r** [comment] 2016-09-15 08:51
@Ostefanini You can test the [bugfix/xlib](https://github.com/SFML/SFML/tree/bugfix/xlib) branch and may fix this issue.

**Comment by eXpl0it3r** [comment] 2016-09-29 07:28
Should be fixed through #1138 in 1dc3db030818297c6ebeae43c85eb3e28b051a07.

**Closed by eXpl0it3r** 2016-09-29 07:28 UTC
Labels: bug, m:sfml-window, p:linux, s:accepted

**Comment by Ostefanini** [comment] 2016-09-29 12:02
I am very interested to use this fix, how to ?

**Comment by eXpl0it3r** [comment] 2016-09-29 12:26
You can compile the [2.4.x branch](https://github.com/SFML/SFML/tree/2.4.x).

**Comment by tapir** [comment] 2016-09-29 12:34
Can we maybe get a 2.4.1 release so that distro pick it up?

**Comment by Ostefanini** [comment] 2016-09-29 12:36
Okay, as ever cmake && make && sudo make install ?

**Comment by MarioLiebisch** [comment] 2016-09-29 12:42
@Ostefanini: Essentially, yes, just don't forget to switch branch first.

Switch to the 2.4.x branch:

    git checkout 2.4.x

Build:

    cmake . && cmake --build .

Install:

    sudo cmake --build . --target install

@tapir: It's planned, but there are a few other open issues for 2.4.1

**Comment by Ostefanini** [comment] 2016-09-29 12:48
Yeah yeah, for sure it was just about the compile part. Love cmake, and love sfml.
