### ISSUE TITLE
[Mac]sf::Keyboard::isKeyPressed(sf::Keyboard::Dash) not responding

### ISSUE THREAD

**Issue by kipbits** [SFML/SFML#974] opened 2015-09-23 23:26 UTC
Hi, this is a bug report related to <a href="http://en.sfml-dev.org/forums/index.php?topic=19024.0">this post</a> in the forums. I can't get the hyphen key on mac to be recognized by SFML. here is a test code:
#include <iostream>
#include <SFML/Window.hpp>
int main(){
    while (true){
        if(sf::Keyboard::isKeyPressed(sf::Keyboard::A)){//1
            std::cout << "aA\n";
        }
        if(sf::Keyboard::isKeyPressed(sf::Keyboard::Dash)){// error???
            std::cout << "-dash-\n";
        }
        if(sf::Keyboard::isKeyPressed(sf::Keyboard::Equal)){
            std::cout << "=\n";
        }
    }
    return 0;
}

I think the problem is something to do with the hyphen case SFML/Window/OSX/HIDInputManager.mm
I've already updated to version-2.3.2. Could someone please look into this?

**Comment by mantognini** [comment] 2015-09-25 08:39
Duplicate of #450 and subset of #7.

**Closed by mantognini** 2015-09-25 08:39 UTC
Labels: bug, m:sfml-window, p:osx, s:undecided
