### ISSUE TITLE
High CPU usage from SoundStream after removal of Audio Device

### ISSUE THREAD

**Issue by Biohazard90** [SFML/SFML#1831] opened 2021-10-14 14:51 UTC
## Subject of the issue

When an audio device is removed while it is being used by a SoundStream, the playback loop will produce error messages without yielding execution resulting in 100% usage on one CPU core.

## Your environment

* Windows 10 x64
* SFML 2.5.1
* VS2019 x86
* Static runtime

## Steps to reproduce

* Play an sf::Music object
* Open the sound device settings in Windows and disable the device that is currently being used as a default device.

## Expected behavior

The music should stop and CPU usage should not change.

## Actual behavior

The CPU usage on one core rises to 100%. The code producing the problem: https://github.com/SFML/SFML/blob/master/src/SFML/Audio/SoundStream.cpp#L335

Sound playback should be stopped or execution should be yielded while errors are occurring due to the device having been removed.

I don't know if any other momentary errors are expected from alGetSourcei. If alGetSourcei is supposed to never fail, then it would make sense to stop playback entirely instead of continuing and yielding.

Also: SFML doesn't seem to handle audio device changes at all. It would be great if SFML would be able to switch the audio device internally when the user switches the default device in Windows.

**Comment by binary1248** [comment] 2022-02-18 03:27
@Biohazard90

Tried to reproduce this on Win10 x64 VS2019 x64 SFML master but I could not reproduce this problem.

When disabling all audio devices the playback of the sound just waits where it is for a device to become available again and continue playing. While waiting, the streaming thread is still running, however it will sleep a bit at the end of every loop so the situation you described with 100% core usage could only be possible using SFML master if one were to set the processing interval to a very low value (or zero).

No OpenAL errors were detected during the test.

If this is not the desired behaviour this would have to be discussed with the OpenAL developers.

I'm closing this issue for now. Feel free to re-open it if you can provide a test scenario that causes the problem using the current master revision.

**Comment by Biohazard90** [comment] 2022-02-21 18:57
@binary1248 Thank you! I took some attempts to test your PR but unfortunately it doesn't solve the issue on my current system, even when I use the official 1.21.1 OpenAL release and replace the headers, lib and DLL shipped with SFML with the official builds provided by the OpenAL developers.

For some reason, contrary to what was happening when I opened this issue, I'm not getting any errors anymore. What I'm experiencing now is solely that SoundSource::getStatus() returns Stopped, but no errors are being generated.

I can't pin point which change on my end could have led to this change in behavior. I don't have the same dedicated sound card anymore that I was using while opening this issue, but I cannot reproduce the OpenAL error code with any of the other devices currently available to me, so it seems unlikely to be related to that.

Depending on how you wish to proceed, please let me know if I can help test or check out anything else. Concerning myself, I will continue by just removing the condition before sleep() is called for the time being.

**Comment by binary1248** [comment] 2022-03-15 18:42
I could reproduce _a_ problem with the latest OpenAL and I fixed the problem I reproduced. I can't say anything about other cases for which I don't have a minimal example that reproduces the reported issue.

**Closed** 2022-04-06 09:50 UTC
Labels: bug, m:sfml-audio, s:undecided, p:windows

**Comment by eXpl0it3r** [comment] 2023-11-13 21:42
We might want to consider backporting this to SFML 2, as it can be a real issue, e.g. with Bluetooth headset running out of battery, and given that way move away from OpenAL (#2749) it's not exactly useful on just SFML 3
