### ISSUE TITLE
Vorbis dynamically linked to a local path file for macos x86_64

### ISSUE THREAD

**Issue by jtmaston** [SFML/SFML#1835] opened 2021-10-19 08:37 UTC
----

## Subject of the issue

When building an app using static libs on macos, in universal binary format, the app runs under arm64, but not x86_64, listing the error as a dylib that wasn't found. Said dylib is listed as having path
 /Users/sfml/Desktop/deps/build_deps/libogg-1.3.3/build/1.3.3/x86_64/root/lib/libogg.0.dylib. 

## Your environment

* MacOS 11.6
* Git master
* Apple clang 13.0.0

## Steps to reproduce

Compile a sfml app to universal binary ( I have a custom xcodeproj that builds both sfml from github and the app I'm running ). Run using rosetta.

## Expected behavior

App should run.

## Actual behavior

App fails to run with dylib not found error. Note: the arm64 app runs.

## Note

Here's the output from otool -L on the vorbis file found inside the framework file. Note how for arm64 the dylibs are all referenced with @rpath, however for x86 ogg is listed as /Users/sfml

![image](https://user-images.githubusercontent.com/43366646/137874119-6ee222de-4a73-4344-aee3-1e542d72cf90.png)

## Edit: vorbisenc seems to have the same issue
<img width="956" alt="image" src="https://user-images.githubusercontent.com/43366646/137874674-16306799-b243-4dfc-8456-ecb2c1129d89.png">

**Comment by eXpl0it3r** [comment] 2021-11-13 15:01
@jtmaston parameters did you set to get the path to use `@rpath` instead?

**Comment by eXpl0it3r** [comment] 2021-11-13 15:39
Never mind, I've found the error in the build script I used. As the universal binary returns one path per architecture, it failed to properly handle the install_name_tool replacement.

As this is really just a duplicate of #1815, I'll close this one and track the fix on the other issue.

Thanks for bringing this up and giving hope that it's (easily) fixable 😄

**Closed by eXpl0it3r** 2021-11-13 15:39 UTC
Labels: bug, p:macos, s:accepted, m:config

**Comment by eXpl0it3r** [comment] 2021-11-13 15:54
Can you give #1843 a try?

**Comment by eXpl0it3r** [comment] 2021-11-14 17:33
Fixed with 600d0f3baf3c1592d2f2c10e4d53daa940bcb0f4
