### ISSUE TITLE
Fail to create render window with a native handle on Linux

### ISSUE THREAD

**Issue by fallahn** [SFML/SFML#1016] opened 2015-12-08 15:39 UTC
As discussed with Tank on IRC:

This could, of course, be the fault of a third party library but:

OS: Ubuntu 15.10 64bit, Compiler: gcc 5, SFML 2.3.2
Using the [nana UI library](https://github.com/cnjinhao/nana) trying to create a control with a render window attached fails with:

X Error of failed request:  BadAccess (attempt to access private resource denied)
  Major opcode of failed request:  2 (X_ChangeWindowAttributes)
  Serial number of failed request:  61
  Current serial number in output stream:  69
terminate called without an active exception
Aborted (core dumped)

Stepping into RenderWindow::create() the debugger points to the constructor of ContextSettings before throwing the error.

Call stack:
#0 0x7ffff66b9267	__GI_raise(sig=sig@entry=6) (../sysdeps/unix/sysv/linux/raise.c:55)
#1 0x7ffff66baeca	__GI_abort() (abort.c:89)
#2 0x7ffff6cf4b7d	__gnu_cxx::__verbose_terminate_handler() () (/usr/lib/x86_64-linux-gnu/libstdc++.so.6:??)
#3 0x7ffff6cf29c6	??() (/usr/lib/x86_64-linux-gnu/libstdc++.so.6:??)
#4 0x7ffff6cf2a11	std::terminate() () (/usr/lib/x86_64-linux-gnu/libstdc++.so.6:??)
#5 0x86a4e1	std::thread::~thread() () (??:??)
#6 0x86e60e	std::default_delete<std::thread>::operator()(std::thread*) (??:??)
#7 0x86c241	std::unique_ptr<std::thread, std::default_delete<std::thread> >::~unique_ptr() () (??:??)
#8 0x86c082	nana::detail::msg_dispatcher::~msg_dispatcher() () (??:??)
#9 0x8657fd	nana::detail::platform_spec::~platform_spec() () (??:??)
#10 0x7ffff66bdd32	__run_exit_handlers(status=1, listp=0x7ffff6a48698 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) (exit.c:82)
#11 0x7ffff66bdd85	__GI_exit(status=<optimised out>) (exit.c:104)
#12 0x7ffff7459b18	_XDefaultError() (/usr/lib/x86_64-linux-gnu/libX11.so.6:??)
#13 0x7ffff7459c4d	_XError() (/usr/lib/x86_64-linux-gnu/libX11.so.6:??)
#14 0x7ffff7456ad7	??() (/usr/lib/x86_64-linux-gnu/libX11.so.6:??)
#15 0x7ffff7456b95	??() (/usr/lib/x86_64-linux-gnu/libX11.so.6:??)
#16 0x7ffff7457555	_XEventsQueued() (/usr/lib/x86_64-linux-gnu/libX11.so.6:??)
#17 0x7ffff745a385	_XGetRequest() (/usr/lib/x86_64-linux-gnu/libX11.so.6:??)
#18 0x7ffff743e495	_XGetWindowAttributes() (/usr/lib/x86_64-linux-gnu/libX11.so.6:??)
#19 0x7ffff743e6a1	XGetWindowAttributes() (/usr/lib/x86_64-linux-gnu/libX11.so.6:??)
#20 0x7ffff74828c3	??() (/usr/lib/x86_64-linux-gnu/libX11.so.6:??)
#21 0x7ffff74832d0	_XimSetICDefaults() (/usr/lib/x86_64-linux-gnu/libX11.so.6:??)
#22 0x7ffff748333e	_XimSetICDefaults() (/usr/lib/x86_64-linux-gnu/libX11.so.6:??)
#23 0x7ffff747ebda	_XimLocalCreateIC() (/usr/lib/x86_64-linux-gnu/libX11.so.6:??)
#24 0x7ffff7464653	XCreateIC() (/usr/lib/x86_64-linux-gnu/libX11.so.6:??)
#25 0x7ffff7978228	sf::priv::WindowImplX11::WindowImplX11(unsigned long) () (/usr/local/lib/libsfml-window.so.2.3:??)
#26 0x7ffff796e551	sf::priv::WindowImpl::create(unsigned long) () (/usr/local/lib/libsfml-window.so.2.3:??)
#27 0x7ffff796e19e	sf::Window::create(unsigned long, sf::ContextSettings const&) () (/usr/local/lib/libsfml-window.so.2.3:??)
#28 0x767e9c	PreviewWindow::start(this=0x7fffffffe478, parent=...) (/home/captain/bgrll/bgrll/src/PreviewWindow.cpp:40)
#29 0x7512f2	MainWindow::MainWindow()::{lambda()#1}::operator()() const() (/home/captain/bgrll/bgrll/src/MainWindow.cpp:49)

The following can be used to reproduce the problem:

    #include <nana/gui/wvl.hpp>
    #include <SFML/Graphics/RenderWindow.hpp>

    int main()
    {   
        nana::form form;

        sf::RenderWindow rw;
        rw.create(reinterpret_cast<sf::WindowHandle>(form.native_handle()));

        form.events().destroy([&rw]() { rw.close(); });
        form.events().focus([&rw]() {rw.clear(sf::Color(50, 60, 50)); rw.display(); });

        form.show();
        nana::exec();

        return 0;
    }

The above works fine on Windows using VS2015 (as does my actual use case).

Possibly related is the X11 example which builds and runs, but closing the window leaves the SFML windows behind:
![](http://djfallen.com/images/x11.png)

**Comment by LaurentGomila** [comment] 2015-12-08 19:11
Since the X11 example works, and, as you say, *This could, of course, be the fault of a third party library*, I don't know if this can be considered a bug. Look at Qt or wxWidgets with SFML: integrating it with a 3rd-party library always involves some extra work. And even then, we have no control on what the library does, and therefore there's no guarantee that it won't break something that SFML needs in order to work without problems.

I don't know what Tank said, but I feel like this should be discussed on the forum first ;)

**Comment by TankOs** [comment] 2016-01-21 13:21
The X11 example works for me, but I can confirm the crash with nana. I have no idea yet where it originates from.

**Comment by binary1248** [comment] 2016-10-02 12:38
Bump.

@fallahn can you test this against the current 2.4.x? SFML reverted back to using Xlib and Xlib is known to have a usable Input Method implementation in contrast to XCB.

**Comment by fallahn** [comment] 2016-10-02 14:05
Just tried this with the lastest revisions of SFML and nana, the output remains the same as the original post.

**Comment by binary1248** [comment] 2016-10-03 13:24
I could sort of reproduce the issue with a similar X error but a different SFML trace.

The problem with this combination is:
* nana creates it's own background std::thread to continuously pump events
* the background thread only synchronizes with nana's own data, not external data
* nana doesn't like to share ownership of its window handle to the extent that SFML needs it to

The native_handle() method was probably written with adding OS specific controls in mind rather than actually sharing the window resource, as such they haven't made any provisions to ensure that doing the latter works properly or is even possible.

There is no technical way to combine SFML like this.

**Comment by binary1248** [comment] 2016-10-09 23:21
Since this issue seems to be "unfixable", I'll close this for now. Feel free to re-open it if you feel that there is technically a way to achieve clean interoperation between SFML and nana.

**Closed by binary1248** 2016-10-09 23:21 UTC
Labels: bug, m:sfml-window, p:linux, s:undecided
