### ISSUE TITLE
sf::Sound does not play mono sf::SoundBuffer when previously played stereo sf::SoundBuffer

### ISSUE THREAD

**Issue by varnholt** [SFML/SFML#2319] opened 2022-12-27 13:11 UTC
## Subject of the issue
sf::Sound does not play mono sf::SoundBuffer when previously played stereo sf::SoundBuffer.

## Your environment

* Windows 11
* SFML 2.5.1
* MSVC 16.11

## Steps to reproduce
I load an sf::SoundBuffer (a stereo sample) into my sf::Sound, play it, all good.
Later I decide to recycle the sf::Sound in order to play another sf::SoundBuffer (a mono sample this time) and play that.

## Expected behavior
I can hear the 2nd sample.

## Actual behavior
I can't hear the 2nd sample.

## Workaround
Just converting all my samples to stereo resolves the problem.

**Comment by eXpl0it3r** [comment] 2022-12-27 21:44
Can't reproduce this with SFML 2.5.1, the 2.6.x branch and latest master (thanks GPT Chat for the example code):

```cpp
#include <SFML/Audio.hpp>

int main()
{
    // Load the stereo sound buffer
    sf::SoundBuffer stereoBuffer;
    if (!stereoBuffer.loadFromFile("stereo.wav"))
    {
        // Error loading the sound buffer
        return 1;
    }

    // Load the mono sound buffer
    sf::SoundBuffer monoBuffer;
    if (!monoBuffer.loadFromFile("mono.wav"))
    {
        // Error loading the sound buffer
        return 1;
    }

    // Create a sound instance
    sf::Sound sound;

    // Play the stereo sound
    sound.setBuffer(stereoBuffer);
    sound.play();

    // Wait for the sound to finish playing
    while (sound.getStatus() == sf::Sound::Playing)
    {
        // Do nothing
    }

    // Play the mono sound
    sound.setBuffer(monoBuffer);
    sound.play();

    // Wait for the sound to finish playing
    while (sound.getStatus() == sf::Sound::Playing)
    {
        // Do nothing
    }
}
```

Sound files used: [mono-stereo.zip](https://github.com/SFML/SFML/files/10310813/mono-stereo.zip)

Does the posted example also cause the issue you're describing?

**Comment by varnholt** [comment] 2022-12-28 15:04
Thanks to you and ChatGPT for trying this out :)
This example works perfectly fine on my end.
While I'll try to come up with a working repro, feel free to close the issue for now.

**Comment by varnholt** [comment] 2022-12-28 15:31
Here's a link to my code:
https://github.com/varnholt/deceptus_engine/blob/master/src/game/audio.cpp
It doesn't do much more than the example above.

**Comment by eXpl0it3r** [comment] 2022-12-28 17:40
Some things one could try:

- I see your code sets a sound position without checking the sample. You can only position mono sounds.
- Maybe there's some issue with setting the looping?
- Or some issue with setting the volume?

**Comment by varnholt** [comment] 2022-12-28 21:17
I have mono samples in my project which have not been played at all by my `Audio` implementation.
Just converting them to stereo resolved the issue for now.

The only difference in my implementation when it comes to playing sound is that an `sf::Sound` has been used a couple of times before it plays a particular sample for the first time. And mono sounds are particularly problematic.

Also:
- The position is an optional which currently never has a value assigned; so that position is never set.
- I've output the volume; for the affected samples 100.0f was passed to SFML.
- None of the non-audible sounds is looped; but I can review that code a bit. I doubt it causes any issue, though.

**Comment by Hapaxia** [comment] 2024-01-31 20:38
If the position is not set, it will be at default (0, 0, 0). This is a problematic value as it's not particularly clear which direction from the listener (also defaults to 0, 0, 0) the mono sound should be (it does, in fact, have no direction since it's at the same location).

Basically, mono sounds that originate from the same position as the listener can cause issues. The solution is to actively and purposefully move it away. Just a tiny amount can be enough; just place it in front of the listener (to get mono in both sides).

**Comment by eXpl0it3r** [comment] 2024-05-12 20:57
> Basically, mono sounds that originate from the same position as the listener can cause issues. The solution is to actively and purposefully move it away. Just a tiny amount can be enough; just place it in front of the listener (to get mono in both sides).

That was probably it, thanks! 🙂 

I'll close this issue for now, if you think there's still something left to do, we can reopen it.

**Closed by eXpl0it3r** 2024-05-12 20:57 UTC
Labels: bug, m:sfml-audio

**Comment by Hapaxia** [comment] 2024-05-17 20:26
I wonder if it would be a good idea to make the default Listener position to be very slightly negative in the z direction so that anyone who does not yet understand the Listener-Sound relationship would still be able to use the positioning of mono sounds intuitively.

Of course, if the Listener should be at exactly 0, there would be a very specific reason and understood by Listener "veterans". :)
