### ISSUE TITLE
Document the automatic channel selection

### ISSUE THREAD

**Issue by kirbyfan64** [SFML/SFML#1009] opened 2015-11-28 19:10 UTC
SFML seems to pick whether or not to use stereo sound based on the sound file. However, it's undocumented; I figured it out by experimenting. Maybe it should be explicitly mentioned?

Discussion at https://github.com/Secretchronicles/TSC/pull/488.

**Comment by eXpl0it3r** [comment] 2015-11-28 20:08
I'm not exactly sure what we should document. If you open a mono file you get a mono source, if you open a stereo file you get a stereo source. I'm not exactly sure at which level the output gets decided but for me both stereo and mono sounds play on both audio output channels.

So what should we add?

**Comment by kirbyfan64** [comment] 2015-11-28 21:00
I was just thinking the part about automatic selection just as an extra sentence. After using SDL (SFML is much better, FYI!) and its mixer weirdness, I kept looking for an option to manually set the channel count; I didn't realize it was automatic.

**Comment by eXpl0it3r** [comment] 2015-11-28 22:08
I don't know how SDL_mixer works, so I still don't really understand.

It feels more like that is only an issue if people expect something differently. It's not exactly a feature that a stereo file gets actually loaded as a stereo file or that a mono file gets actually loaded as a mono file, just because other libraries (apparently) seem to make things complicated.

Additionally a simple sentence such as "channel selection is done automatically" can confuse a lot of people. So I'm still not exactly sure what could be added to help out everyone.

**Comment by Bromeon** [comment] 2015-11-29 16:43
`sf::SoundBuffer::getChannelCount()` does exactly what it says: returning the number of channels in the buffer. I don't see anything confusing here... If the audio file has 2 channels, the channel count will obviously be 2, I don't think it's appropriate to speak of "automatic inference", let alone "undocumented feature"... what other behavior would be reasonable?

By the way, it would be nice to discuss things on the forum until issues are confirmed, see also the [Contribution Guidelines](http://en.sfml-dev.org/forums/index.php?topic=18725.msg135212). Thanks!

**Comment by mantognini** [comment] 2016-01-18 10:21
I close this as it seems no longer relevant. Feel free to discuss it on the forum if otherwise.

**Closed by mantognini** 2016-01-18 10:21 UTC
Labels: not an issue
