### ISSUE TITLE
Positioning and stretching issues due to window resize at RenderWindow::display

### ISSUE THREAD

**Issue by sumitsahrawat** [SFML/SFML#1017] opened 2015-12-08 18:21 UTC
I'm using the following code to render a centered "Hello World" on a window, and it shows one of two possible outputs:

``` cpp
#include "SFML/Graphics.hpp"
#include <iostream>

int main(int, char**) {
    sf::RenderWindow renderWindow(sf::VideoMode(800, 600), "Hello World!");

    sf::Font font;
    font.loadFromFile("sansation.ttf");

    sf::Text text("Hello World!", font, 128);
    text.setColor(sf::Color::Red);
    sf::FloatRect bounds(text.getLocalBounds());
    text.setPosition(renderWindow.getSize().x / 2 - (bounds.left + bounds.width / 2),
                     renderWindow.getSize().y / 2 - (bounds.top + bounds.height / 2));

    while (renderWindow.isOpen()) {
        sf::Event event;

        while (renderWindow.pollEvent(event)) {
            if (event.type == sf::Event::Closed) {
                renderWindow.close();
            }
        }

        renderWindow.clear(sf::Color::White);
        renderWindow.draw(text);
        renderWindow.display();
    }
}
```

I get this output most of the time:

![2015-12-08-233249_958x352_scrot](https://cloud.githubusercontent.com/assets/5645741/11664170/35dc9edc-9e06-11e5-945b-12e326fa6611.png)

But this also turns up once in a while:

![2015-12-08-234325_958x352_scrot](https://cloud.githubusercontent.com/assets/5645741/11664174/3c2e11e4-9e06-11e5-95b5-68ef3a96e0bf.png)

---

I'm using XMonad, which automatically tiles the windows without any decoration. The programs are compiled and executed as follows:

``` bash
g++ -c helloworld.cpp
g++ -o helloworld.o -lsfml-{graphics,system,window}
./a.out
```

**Comment by sumitsahrawat** [comment] 2015-12-08 18:24
This looks like some kind of race condition between the window being displayed and being resized by the window manager.

Putting a debug statement in the main loop, I can determine that the window size is 958x352 as opposed to 800x600.

**Comment by binary1248** [comment] 2015-12-08 23:46
This is perfectly normal. Some window managers choose not to do things until a program starts processing events. You cannot rely on window size information until the event processing loop has begun. Any window size value you get before your event processing starts will not be 100% reliable.

**Comment by Bromeon** [comment] 2015-12-09 09:25
> This is perfectly normal. [...] You cannot rely on window size information until the event processing loop has begun.

@binary1248: Even if it may be comprehensible given knowledge of window manager implementations, this behavior is definitely counter-intuitive for SFML users. Even more so, as it is nowhere documented. No wonder people consider it a bug, because it *actually is*.

The very least we should do is explain such behavior in the documentation. But I don't like an API with vague semantics, where function calls may or may not fail for obscure reasons... Isn't it possible to ensure on SFML side that window size functions return the correct result (even if it's just a hack like running the event loop initially)?

**Comment by LaurentGomila** [comment] 2015-12-09 09:39
Since `m_size` is cached in `sf::Window`, can't we just set it to the `VideoMode` size until event processing triggers an internal update?

**Comment by sumitsahrawat** [comment] 2015-12-09 15:22
> By the way, how does an incorrect window size, and thus in this example an incorrect text position, can lead to the text being stretched??

Exactly. By my reasoning, I expect a positioning issue. The resultant position would be wrong as wrong value of `renderWindow.getSize()` is being used before the main loop.

---

Also, the text stretches whenever the window is resized (by first shifting it to float mode). Is this the expected behavior? It seems unintuitive to me. Also, it might be related to the stretching issue above.

**Comment by sumitsahrawat** [comment] 2015-12-09 16:06
A fix for developing on XMonad is to cause the window to float by default. The WM_CLASS property of the window is equal to the second argument passed to `sf::RenderWindow` constructor as shown above.

**Comment by LaurentGomila** [comment] 2015-12-09 16:24
I think it gets stretched because the default view initially gets created with a wrong size, and then is resized to the requested size. The solution I previously suggested would solve that as well.

**Comment by sumitsahrawat** [comment] 2015-12-09 16:31
I'll take a look. Maybe I can send a PR.

**Comment by eXpl0it3r** [comment] 2015-12-09 18:38
So should we reopen this?

**Comment by sumitsahrawat** [comment] 2015-12-09 19:13
I tried this, which did not work: sumitsahrawat@d1c2475

**Comment by LaurentGomila** [comment] 2015-12-09 20:11
> So should we reopen this?

Yes.

**Comment by TankOs** [comment] 2016-01-21 10:33
> I think it gets stretched because the default view initially gets created with a wrong size, and then is resized to the requested size. The solution I previously suggested would solve that as well.

No it's created using the *correct* size, but gets resized by the tiling window manager. Therefore the view needs updating. The behavior is normal in my opinion and shouldn't be changed. It's like resizing a window manually, the view would stretch as well.

**Comment by LaurentGomila** [comment] 2016-01-21 10:49
> No it's created using the correct size, but gets resized by the tiling window manager

We can't be sure. Maybe the WM has a tile of exactly 800x600, or maybe the SFML window is floating. But yes, this is very likely and thus @sumitsahrawat should check what happens to the window size.

> The behavior is normal in my opinion and shouldn't be changed

Right, but it's still a problem if sometimes it works and sometimes not.

**Comment by sumitsahrawat** [comment] 2016-01-21 12:04
By configuring my WM, I can make windows with a specific `WM_CLASS` open as floating by default. When I do so for the sfml application, it shows no stretching. It seems like @TankOs is right.

Still, I think that the race condition which gives different behaviors should be resolved.

**Comment by TankOs** [comment] 2016-01-21 12:06
Yep, that's definitely an inconsistency that needs to be fixed.

**Comment by eXpl0it3r** [comment] 2016-02-18 17:45
So what's the fix?

**Comment by binary1248** [comment] 2016-10-02 12:35
Bump.

Would like to know whether reverting back to Xlib might have magically (I wouldn't understand how, but it wouldn't be surprising) fixed this issue. @sumitsahrawat can you test this against 2.4.x?

If the issue persists, we should consider how we proceed to fix it.

The main problem is that we cannot always assume that the window is created respecting the dimensions that we passed to the window manager. If it does not respect those dimensions, at least it notifies us of the actual dimensions through a ConfigureNotify event. Those events are also translated to SFML Resized events, however they only lead to m_size being updated and onResize() (and thus the OpenGL viewport being updated) the next time the user actually calls pollEvent() or waitEvent().

There is currently no asynchronous way for the window Impl to notify the Window that the real size is available without user intervention.

As @Bromeon said, a possible solution would be to run the event processing once or a few times right after window creation in order to get our data and the window manager's data into a consistent state. If all else fails, this might be the only viable solution.

**Comment by sumitsahrawat** [comment] 2017-12-04 13:52
I came back to this issue after a long time and sadly I'm not in a state where I'd be able to test it easily without some work. I've since moved on to a windows based system.

**Comment by binary1248** [comment] 2018-04-07 13:04
I tried again to reproduce this issue with the provided code on Linux Mint with XMonad all updated to latest versions with the current master revision and could not get the problem to show itself once. XMonad tiles the created window properly and the text is always centered without any stretching. I think Xlib is taking care of things properly now.

I'll close this for now. If anybody has more information on how or if this can still be reproduced, provide the information here and we can reopen this again.

**Closed by binary1248** 2018-04-07 13:04 UTC
Labels: bug, m:sfml-window, p:linux, s:undecided
