### ISSUE TITLE
sf::Window.create() fails on non-reparenting linux WMs

### ISSUE THREAD

**Issue by TrilbyWhite** [SFML/SFML#1043] opened 2016-01-18 20:02 UTC
I'm working on rewriting one of my projects in SFML2 and have run into the following issue.  When I create a sf::RenderWindow as follows I get an immediate crash:
```c++
win.create(sf::VideoMode::getDesktopMode(), "Title");
```
When I try to run the program I get the following error output:
```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  42 (X_SetInputFocus)
  Serial number of failed request:  96
  Current serial number in output stream:  105
```
I've done a fair bit of experiementing and initially thought it was my WM (a very simple nonreparenting WM).  The WM was not making any calls to XSetInputFoucs, so the source of that Xlib call must be within SFML.  I've found I get the exact same error on other nonreparenting WMs including DWM, while it works as expected on reparenting WMs.

As a workaround I've found the following code works, but is not ideal as the Fullscreen window is completely unmaged by the WM:
```c++
if (getenv("NON_REPARENTING"))
   win.create(sf::VideoMode::getDesktopMode(), "Title", sf::Style::Fullscreen);
else
   win.create(sf::VideoMode::getDesktopMode(), "Title");
```
With this code, it works as long as NON_REPARENTING is set in the environment for nonreparenting WMs.

I've confirmed the same error (and workaround) with the simple example program provided here:
http://www.sfml-dev.org/tutorials/2.3/start-linux.php

**Comment by eXpl0it3r** [comment] 2016-01-18 20:23
A quick search might have brought you to the already existing bug report #991
Also if you haven't, you might want to take a look at the [contribution guidelines](http://www.sfml-dev.org/contribute.php).

Marking this as duplicate.

**Closed by eXpl0it3r** 2016-01-18 20:23 UTC

**Comment by zsbzsb** [comment] 2016-01-18 21:18
@eXpl0it3r I don't see it mentioned anywhere in #991 that the issue is due to NON_REPARENTING being set. I would consider that a helpful piece of information.

**Comment by binary1248** [comment] 2016-01-18 21:28
@zsbzsb This (reading an environment variable) is just a workaround that can be enabled/disabled without having to recompile the code. It is not set by the system.

**Comment by TrilbyWhite** [comment] 2016-01-20 15:20
eXpl0it3r, sorry for the confusion.  As indicated above, the NON_REPARENTING is a completely arbitrary environment variable name that I made up for this.  This environment variable has nothing to do with SFML, but it was my hack to work around the problem I was having.  If the variable is detected, I create the window instead with style::Fullscreen as this issue does not affect Fullscreen windows (which seem to be implemented as override_redirect windows in X11).

**Comment by TrilbyWhite** [comment] 2016-01-20 15:21
eXpl0it3r, sorry for the confusion.  As indicated above, the NON_REPARENTING is a completely arbitrary environment variable name that I made up for this.  This environment variable has nothing to do with SFML, but it was my hack to work around the problem I was having.  If the variable is detected, I create the window instead with style::Fullscreen as this issue does not affect Fullscreen windows (which seem to be implemented as override_redirect windows in X11).

I'm not familiar with the SFML code, but this might be informative: a override_redirect window is assumed to not be reparented (they never should be - windows managers should not touch override_redirect windows) and thus whatever triggers this error is not invoked.

**Comment by TrilbyWhite** [comment] 2016-01-20 15:21
eXpl0it3r, sorry for the confusion.  As indicated above, the NON_REPARENTING is a completely arbitrary environment variable name that I made up for this.  This environment variable has nothing to do with SFML, but it was my hack to work around the problem I was having.  If the variable is detected, I create the window instead with style::Fullscreen as this issue does not affect Fullscreen windows (which seem to be implemented as override_redirect windows in X11).

I'm not familiar with the SFML code, but this might be informative: a override_redirect window is assumed to not be reparented (they never should be - windows managers should not touch override_redirect windows) and thus whatever triggers this error is not invoked.

**Comment by zsbzsb** [comment] 2016-01-20 15:53
@binary1248 I think you misunderstood, I was merely referring to the fact that #991 seems to be caused by a non reparenting WM, not simply because of an arbitrary environment variable. That piece of information isn't mentioned anywhere in the other issue.

**Comment by TrilbyWhite** [comment] 2016-01-20 16:24
Oops, my previous reply was wrongly directed, that was for you zsbzsb.  But again, the environment variable is not at all relevant for #991.  I could have just as easily done the work around in my code with something from my programs own configuration rather than from an environment variable.  Alternatively, I could just hardcode the use of fullscreen window.  The environment variable is only what I used on my system for my program to indicate a non-reparenting WM was in use: it is - again - completely irrelevant to the actual issue in SFML and to #991

**Comment by TrilbyWhite** [comment] 2016-01-20 16:37
Oops, my previous reply was wrongly directed, that was for you zsbzsb.  But again, the environment variable is not at all relevant for #991.  I could have just as easily done the work around in my code with something from my programs own configuration rather than from an environment variable.  Alternatively, I could just hardcode the use of fullscreen window.  The environment variable is only what I used on my system for my program to indicate a non-reparenting WM was in use: it is - again - completely irrelevant to the actual issue in SFML and to #991

**Comment by eXpl0it3r** [comment] 2016-01-20 16:42
Could you please post just once, so I don't have to go and delete your other posts (again)? :wink:
