### ISSUE TITLE
sign conversion error prevents build

### ISSUE THREAD

**Issue by VictorEijkhout** [SFML/SFML#2582] opened 2023-06-22 14:11 UTC
```
/Users/eijkhout/Installation/sfml/sfml-2.6.0/src/SFML/System/Unix/ClockImpl.cpp: In static member function 'static sf::Time sf::priv::ClockImpl::getCurrentTime()':
/Users/eijkhout/Installation/sfml/sfml-2.6.0/src/SFML/System/Unix/ClockImpl.cpp:50:41: error: conversion to 'sf::Int64' {aka 'long long int'} from 'sf::Uint64' {aka 'long long unsigned int'} may change the sign of the result [-Werror=sign-conversion]
   50 |     return sf::microseconds(nanoseconds / 1000);
      |                             ~~~~~~~~~~~~^~~~~~
cc1plus: all warnings being treated as errors
```

**Comment by ChrisThrasher** [comment] 2023-06-22 14:12
Can you please provide information on your system and how someone may go about reproducing this?

**Comment by VictorEijkhout** [comment] 2023-06-22 15:15
I was building with gcc 12 on MacOS.

**Comment by ChrisThrasher** [comment] 2023-06-22 15:21
GCC fails on macOS for reasons related to Apple system headers. Once you disable `WARNINGS_AS_ERRORS` you'll probably run into them. Use AppleClang or Clang instead.

**Comment by VictorEijkhout** [comment] 2023-06-22 15:22
Ah. Just ran into that indeed. I'll try clang.

**Comment by ChrisThrasher** [comment] 2023-06-22 15:41
We'd like to support GCC on macOS but simply don't know how to fix the compilation errors. I'm closing this issue since it seems like the error was limited to that compiler+OS combo.

**Closed by ChrisThrasher** 2023-06-22 15:41 UTC
Labels: bug, p:macos

**Comment by barracuda156** [comment] 2023-08-07 11:29
Why was this closed? It looks like a bug to fix.

**Comment by eXpl0it3r** [comment] 2023-11-16 22:04
See also: #2790
