### ISSUE TITLE
Calling Window.setSize() while resizing makes the window grow on Linux

### ISSUE THREAD

**Issue by Chnossos** [SFML/SFML#2124] opened 2022-06-08 11:45 UTC
## Calling Window.setSize() while resizing makes the window grow

[[Original forum thread](https://en.sfml-dev.org/forums/index.php?topic=28276)]

I want to restrict the size of the window so it doesn't shrink more than a certain size.
Using the following code, when I start to resize horizontally (mouse button pressed then mouse move) the window will grow in height until it reaches the top of the screen or until I release the resize handle (mouse button released).

```cpp
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode(1280, 720, sf::VideoMode::getDesktopMode().bitsPerPixel), "W");

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            /**/ if (event.type == sf::Event::Closed)
                window.close();
            else if (event.type == sf::Event::Resized)
            {
                if (event.size.width < 1280 || event.size.height < 720)
                    window.setSize({ 1280, 720 });
            }
        }
        window.clear(sf::Color::White);
        window.display();
    }
}
```

## Your environment

* Fedora 32 (Wayland)
* SFML 2.5.1 (conan)
* `g++ (GCC) 10.3.1 20210422 (Red Hat 10.3.1-1)`
* No special compiler flags used

## Steps to reproduce

conanfile.txt
```ini
[requires]
sfml/2.5.1

[generators]
cmake
```

CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.0)
project(sfml-resize-bug)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)

add_executable(${PROJECT_NAME} main.cpp)
conan_target_link_libraries(${PROJECT_NAME})
```

Compile, build & launch
```bash
$ conan install -if build .
$ cmake -B build
$ cmake --build build
$ ./build/bin/sfml-resize-bug
```

## Expected behavior

Window should not shrink more than size specified in `window.setSize({ ... })` call. It should not grow on its own either.

## Actual behavior

![Screencast from 08-06-22 13 22 22](https://user-images.githubusercontent.com/7984363/172608310-f2d1078a-a979-4ddd-9d3a-c1477da9968e.gif)

**Comment by EtoileScintillante** [comment] 2022-06-09 06:57
I tried out your code and  first it would not compile:

`
test.cpp:5:29: error: no matching constructor for initialization of 'sf::VideoMode'
    sf::RenderWindow window(sf::VideoMode(1280, 720, sf::VideoMode::getDesktopMode().bitsPerPixel), "W");
`

After fixing that everything seemed worked fine. I resized the window (made it wider) and the height stayed at 720. I am on macOS though.

**Comment by danieljpetersen** [comment] 2022-06-10 08:34
I think you might have compiled against master EtoileScintillante. The sample code compiled fine for me when linked against 2.5.1. I think that constructor was changed in the master branch.

---

It's possible I'm just tired and missing something obvious, but something strange may be going on with window.setSize on Linux. I'm on x11 (Cinnamon) and when I ran the sample code the window would not resize from the setSize(...) function call, it always remained the size I dragged the border to. I thought maybe this was because the call was in the event loop so I moved the resize block out and nothing changed. 

If I call setSize on its own it works, but if I call setSize as a condition of querying the current window size then the setSize call has no effect. Calling window.getSize() after calling window.setSize(...) after will report the requested size, but the actual window size on my screen remains the size that I dragged the window to. Possibly a different bug but I figure it's relevant here. 

```cpp
#include <SFML/Graphics.hpp>

#include <iostream>

int main()
{
    sf::RenderWindow window(sf::VideoMode(1280, 720, sf::VideoMode::getDesktopMode().bitsPerPixel), "W");

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        auto xWindowSize = window.getSize().x;
        if (xWindowSize < 1280) // comment out this if statement and setSize works correctly
        {
            std::cout << "window size before: " << std::to_string(xWindowSize) << std::endl;
            window.setSize(sf::Vector2u(1280, 720));
            std::cout << "window size after: " << std::to_string(window.getSize().x) << std::endl;
        }

        window.clear(sf::Color::White);
        window.display();
    }
}
```

**Comment by eXpl0it3r** [comment] 2022-06-10 09:29
@EtoileScintillante Thanks for trying to reproduce this issue, it however might be a Linux or rather X11 related issue, so won't be reproducible on macOS.

As X11 is an asynchronous protocol, there's always a chance that changing things and immediately requesting an update (e.g. setSize + getSize) can result in a temporarily inconsistent state.

@Chnossos can you try the `2.6.x` branch, as we've done quite a bit of bugfixing on that branch.
@danieljpetersen are you saying that `setSize` never changes the window size on `master`?

**Comment by danieljpetersen** [comment] 2022-06-10 18:23
>  @danieljpetersen are you saying that setSize never changes the window size on master?

I don't understand it. setSize will work correctly if called on its own, but when called as a condition of testing against the current size (so the example I posted) it doesn't work. 

* 2.5.1 and 2.6.x have identical behavior, so setSize had no visible effect in the example I posted.
* master possibly has identical behavior, but it did behave correctly on one of my border drags. I was then unable to replicate it working correctly, even with restarting the program, so it's possible that it only very rarely behaves correctly across 2.5.1, 2.6.x, and 3.

![2022-06-10 13-48-06](https://user-images.githubusercontent.com/5576311/173124872-7f3c545e-580e-4fe9-acfe-005124f00701.gif)

Because it's not clear from that video, note that I released the mouse button multiple times in that video, it's showing multiple different border drags. Hopefully you see what I mean though. There's an if statement checking whether getSize().x < 1280. This will evaluate to true, at which point setSize(1280, 720) gets hit. This call almost always will have no visible effect on the window size, but it will change the reported getSize() return values. 

I took a look at the SFML code for setSize on x11 and it's pretty straight forward and seems like it should work. I then took a look at the SDL2 code for this and it's more or less the same, but they do two extra calls in order to mitigate quirks with different window managers, https://github.com/davidsiaw/SDL2/blob/master/src/video/x11/SDL_x11window.c#L876. Basically, if I'm understanding it correctly, in addition to the call to XResizeWindow, they also do a call to X11_XMoveWindow (to the current position it is in) and then X11_XRaiseWindow (even though it's already raised). If you click the link there's a comment there explaining this.

I'm now thinking that because I'm on x11 and the original issue was on wayland, it's probably a different issue that I'm running into. I'm only posting here because I ran into this while trying to test this.

**Comment by Chnossos** [comment] 2022-07-02 13:42
> @Chnossos can you try the `2.6.x` branch, as we've done quite a bit of bugfixing on that branch.

Sorry for the long delay. Here is what I just did:

```shell
cd ~/lib
git clone -b 2.6.x --depth 1 --single-branch https://github.com/SFML/SFML.git && cd SFML
cmake -B build -G Ninja \
  -DCMAKE_BUILD_TYPE=Release \
  -DBUILD_SHARED_LIBS=OFF \
  -DCMAKE_INSTALL_PREFIX=$PWD/install \
  -DSFML_BUILD_AUDIO=OFF \
  -DSFML_BUILD_NETWORK=OFF \
  -DSFML_USE_SYSTEM_DEPS=ON \
  -DSFML_INSTALL_PKGCONFIG_FILES=OFF
cmake --build build --target install
```
Then updated the project's `CMakeLists.txt` like so:
```cmake
cmake_minimum_required(VERSION 3.0)
project(sfml-resize-bug)

set(SFML_STATIC_LIBRARIES TRUE)
set(SFML_DIR "$ENV{HOME}/lib/SFML/install/lib64/cmake/SFML")
find_package(SFML 2 COMPONENTS graphics REQUIRED)

add_executable(${PROJECT_NAME} main.cpp)
target_link_libraries(${PROJECT_NAME} sfml-graphics)
```
Weirdly enough, here is what happens if I try to require a `2.6` version:
```
CMake Error at CMakeLists.txt:9 (find_package):
  Could not find a configuration file for package "SFML" that is compatible
  with requested version "2.6".

  The following configuration files were considered but not accepted:

    /home/pierre/lib/SFML/install/lib64/cmake/SFML/SFMLConfig.cmake, version: 2.5.1
```
With all that said, no change in behavior.

**Comment by DreamHollow** [comment] 2022-08-21 19:25
It should be noted here that your implementation of forced window resizing is a bit awkward, so I wanted to make a suggestion and see if it helps resolve the buggy response.

In the following code in the original post, you have it formatted like this:
```
    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            /**/ if (event.type == sf::Event::Closed)
                window.close();
            else if (event.type == sf::Event::Resized)
            {
                if (event.size.width < 1280 || event.size.height < 720)
                    window.setSize({ 1280, 720 });
            }
        }
        window.clear(sf::Color::White);
        window.display();
    }
```
There are a couple of things you could do to optimize this a bit better, I think. People seem to forget that the Event class is designed to work well with the switch([value]) statement. Also, sf:;Vector2u is specifically designed for use in functions and statements related to directly interacting with window parameters.

Try:
```
`    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            switch(event.type) // Regularly able to alternate between Events
              case sf::Event::Closed:
              {
                window.close();
                break;
              }
             case sf::Event::Resized:
                if (event.size.width < 1280 || event.size.height < 720)
                {
                    window.setSize(sf::Vector2u(1280, 720));
                }
        }
        window.clear(sf::Color::White);
        window.display();
    }`
```
This is slightly cleaner code and slightly less problematic. Vector2u is really helpful when dealing with window resizing in general, as it's specifically designed for the library to interpret window parameters more exactly.

Let me know if this helps fix the problem.

**Comment by Chnossos** [comment] 2022-09-01 08:57
@DreamHollow Thank you for the kind attempt at helping :)

Those two suggestions cannot change anything to the actual behavior as they are mainly cosmetic:  
- There are very few differences between two `if`s and a switch in resulting machine code, and a smart compiler will easily recognize this pattern and convert them to a jump table anyway ;
- `sf::Vector2u`'s selected [constructor][1] being **not marked _explicit_**,  
`foo(sf::Vector2u(0, 0))` and `foo(sf::Vector2u { 0, 0 }` and `foo({ 0, 0 })` are strictly equivalent, meaning they call the same constructor.

My aim was to make a [Minimal Reproducible Example][2] code, thus premature optimization would especially be a mistake here as it would clutter the code instead of simplifying it.

---

> Also, sf:;Vector2u is specifically designed for use in functions and statements related to directly interacting with window parameters.

That is, unfortunately, not true. Looking at `sf::Vector2<T>`, its goal is to represent a 2D vector in space. It is also used in places where a coordinate, or more generally, a pair of values of the same type is expected because in the end, it is just a glorified `std::pair<T, T>` in terms of memory layout, and you're probably playing around with this type a lot in SFML code anyway (e.g. `Window::getSize()` returns a `sf::Vector2u`.

> Vector2u is really helpful when dealing with window resizing in general, as it's specifically designed for the library to interpret window parameters more exactly.

Well, my code does use Vector2u :^) Be careful not to overinterpret things since you're still learning!

[1]: https://github.com/SFML/SFML/blob/master/include/SFML/System/Vector2.hpp#L61
[2]: https://en.wikipedia.org/wiki/Minimal_reproducible_example

**Comment by dgcor** [comment] 2022-09-08 22:53
I have this problem too. Only on Linux. The problem seems to be the lack of a `is resizing` event, like the windows implementation has, that prevent the resize events from being triggered until the mouse is released.

You can see it in action using a pre built AppImage from one of these 3:
https://github.com/dgcor/Columns
https://github.com/dgcor/DGEngine
https://github.com/dgcor/Diabolika

**Comment by dogunbound** [comment] 2022-10-12 14:10
Same issue on ArchLinux + kde + xorg. setSize doesn't work after the resize event has been called.
Here is a funny video you can watch: https://youtu.be/9EbQfLMeZJE

This is a min reproducible that showcases setSize not working
```c++
#include <SFML/Graphics.hpp>

int main() {
  sf::RenderWindow window(sf::VideoMode(200, 200), "SFML works!");

  bool increment_positive = true;
  while (window.isOpen())
  {
    sf::Event event;
    while (window.pollEvent(event))
    {
      if (event.type == sf::Event::Closed)
        window.close();
      if (event.type == sf::Event::Resized) {
        const sf::Vector2u window_size(event.size.width, event.size.height);

        if (window_size.x < 200) {
          window.setSize(sf::Vector2u(200, window_size.y));
          printf("AYO\n");
        }
        if (window_size.y < 200) {
          window.setSize(sf::Vector2u(window_size.x, 200));
          printf("AYO\n");
        }
      }
    }

    window.clear();
    window.display();
  }

  return 0;
}
```

Funnily enough, it's not like the function itself doesn't work. This min reproducible shows setSize working:
```c++
#include <SFML/Graphics.hpp>

int main() {
  sf::RenderWindow window(sf::VideoMode(200, 200), "SFML works!");

  sf::Vector2u window_size(1, 1);
  bool increment_positive = true;
  while (window.isOpen())
  {
    sf::Event event;
    while (window.pollEvent(event))
    {
      if (event.type == sf::Event::Closed)
        window.close();
    }

    window.clear();
    window.display();

    window.setSize(window_size);
    if (window_size.x > 2000) increment_positive = false;
    if (window_size.x < 100) increment_positive = true;
    if (increment_positive) {
      window_size.x += 100;
      window_size.y += 100;
    } else {
      window_size.x -= 100;
      window_size.y -= 100;
    }
    printf("%d %d\n", window_size.x, window_size.y);


    sf::sleep(sf::milliseconds(500));
  }

  return 0;
}
```

**Comment by DreamHollow** [comment] 2022-10-12 18:28
I think I may have fixed it.

Please try out this modified code and let me know if it works as intended on your end.

`#include <SFML/Graphics.hpp>
#include <SFML/Window.hpp>
#include <SFML/System.hpp>

int main()
{
    sf::VideoMode vid_mode;
    vid_mode.width = 1280;
    vid_mode.height = 720;
    vid_mode.bitsPerPixel = 32;
    sf::RenderWindow window(vid_mode, "NO TITLE", sf::Style::Resize | sf::Style::Close);

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();
            else if (event.type == sf::Event::Resized)
            {
                if (event.size.width < 1280 || event.size.height < 720)
                    window.setSize({ 1280, 720 });
                else if(event.size.width < 1280 && event.size.height < 720)
                    window.setSize({ 1280, 720 });
            }
        }
        window.clear(sf::Color::White);
        window.display();
    }
}`

**Comment by dogunbound** [comment] 2022-12-24 04:37
> Tried it, no change in behavior (`sf::VideoMode::getDesktopMode().bitsPerPixel()` is equal to `32` on my system anyway).
> 
> I did some tests on my own, the bug appears precisely because of the call to `window.setSize()` while manually resizing the window (mouse button not released yet). To see this theory in practice, use this code:
> 
> ```c++
> #include <SFML/Graphics.hpp>
> #include <SFML/System/Clock.hpp>
> 
> int main()
> {
>     sf::RenderWindow window(sf::VideoMode(1280, 720, sf::VideoMode::getDesktopMode().bitsPerPixel), "W");
> 
>     sf::Time  elapsedTime;
>     sf::Clock clock;
>     while (window.isOpen())
>     {
>         sf::Event event;
>         while (window.pollEvent(event))
>         {
>             /**/ if (event.type == sf::Event::Closed)
>                 window.close();
>         }
>         window.clear(sf::Color::White);
>         window.display();
> 
>         if ((elapsedTime += clock.restart()) >= sf::seconds(2))
>         {
>             elapsedTime -= sf::seconds(2);
>             window.setSize({ 1280, 720 });
>         }
>     }
> }
> ```
> 
> If you resize and release the handle quickly enough, then the window gets resized without problem. If you keep the mouse button pressed, then at each call to `setSize()` the window grows in height by a small margin (maybe ~20px?).
> 
> The growth factor is not big but with the initial code `setSize()` got called a huge amount of time in a small amount of time, hence the big growth.

Can confirm that the issue is precisely what you mentioned. The setSize function does get called just fine, but because the user is still holding their mouse button, Xorg does another resize that doesn't get polled. Thus, you get a resize event that the programmer cannot detect. I don't know a good fix still.

**Comment by dogunbound** [comment] 2023-01-01 01:07
With the PR I made, the issue will only occur if the user holds onto the window for more than 50 milliseconds after a resize event has been called.

**Comment by eXpl0it3r** [comment] 2023-02-02 22:16
@Chnossos can you give #2378 a try and see if that solves your issue?

**Comment by Chnossos** [comment] 2023-02-24 17:03
Here is what I did:

```shell
cd ~/lib
git clone -b 2.6.x --depth 1 --single-branch https://github.com/SFML/SFML.git && cd SFML
# EDIT src/SFML/Window/Unix/WindowImplX11.cpp to add the [changes](https://github.com/SFML/SFML/pull/2378/files)
cmake -B build -G Ninja \
  -DCMAKE_BUILD_TYPE=Release \
  -DBUILD_SHARED_LIBS=OFF \
  -DCMAKE_INSTALL_PREFIX=$PWD/install \
  -DSFML_BUILD_AUDIO=OFF \
  -DSFML_BUILD_NETWORK=OFF \
  -DSFML_USE_SYSTEM_DEPS=ON \
  -DSFML_INSTALL_PKGCONFIG_FILES=OFF
cmake --build build --target install
```
Then updated the project's `CMakeLists.txt` like so:
```cmake
cmake_minimum_required(VERSION 3.0)
project(sfml-resize-bug)

set(SFML_STATIC_LIBRARIES TRUE)
set(SFML_DIR "$ENV{HOME}/lib/SFML/install/lib64/cmake/SFML")
find_package(SFML 2 COMPONENTS graphics REQUIRED)

add_executable(${PROJECT_NAME} main.cpp)
target_link_libraries(${PROJECT_NAME} sfml-graphics)
```

Now the weird resize still happens, but then the window resizes itself to what I specified, so we could say "close enough"?

**Comment by dogunbound** [comment] 2023-03-06 02:13
> Here is what I did:
> 
> ```shell
> cd ~/lib
> git clone -b 2.6.x --depth 1 --single-branch https://github.com/SFML/SFML.git && cd SFML
> # EDIT src/SFML/Window/Unix/WindowImplX11.cpp to add the [changes](https://github.com/SFML/SFML/pull/2378/files)
> cmake -B build -G Ninja \
>   -DCMAKE_BUILD_TYPE=Release \
>   -DBUILD_SHARED_LIBS=OFF \
>   -DCMAKE_INSTALL_PREFIX=$PWD/install \
>   -DSFML_BUILD_AUDIO=OFF \
>   -DSFML_BUILD_NETWORK=OFF \
>   -DSFML_USE_SYSTEM_DEPS=ON \
>   -DSFML_INSTALL_PKGCONFIG_FILES=OFF
> cmake --build build --target install
> ```
> 
> Using the `main.cpp` from my first post and the following `CMakeLists.txt`:
> 
> ```cmake
> cmake_minimum_required(VERSION 3.0)
> project(sfml-resize-bug)
> 
> set(SFML_STATIC_LIBRARIES TRUE)
> set(SFML_DIR "$ENV{HOME}/lib/SFML/install/lib64/cmake/SFML")
> find_package(SFML 2 COMPONENTS graphics REQUIRED)
> 
> add_executable(${PROJECT_NAME} main.cpp)
> target_link_libraries(${PROJECT_NAME} sfml-graphics)
> ```
> 
> Now the weird resize still happens, but then the window resizes itself to what I specified, so we could say "close enough"?

I think the weird resize you are talking about is due to a bug in your resize code. Try this instead:
```c++
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode(1280, 720, sf::VideoMode::getDesktopMode().bitsPerPixel), "W");

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            /**/ if (event.type == sf::Event::Closed)
                window.close();
            else if (event.type == sf::Event::Resized)
            {
                if (event.size.width < 1280)
                    window.setSize({ 1280, event.size.height });
                if (event.size.height < 720)
                    window.setSize({ event.size.width, 720 });
            }
        }
        window.clear(sf::Color::White);
        window.display();
    }
}```

**Comment by dogunbound** [comment] 2023-03-20 14:27
> > Here is what I did:
> > ```shell
> > cd ~/lib
> > git clone -b 2.6.x --depth 1 --single-branch https://github.com/SFML/SFML.git && cd SFML
> > # EDIT src/SFML/Window/Unix/WindowImplX11.cpp to add the [changes](https://github.com/SFML/SFML/pull/2378/files)
> > cmake -B build -G Ninja \
> >   -DCMAKE_BUILD_TYPE=Release \
> >   -DBUILD_SHARED_LIBS=OFF \
> >   -DCMAKE_INSTALL_PREFIX=$PWD/install \
> >   -DSFML_BUILD_AUDIO=OFF \
> >   -DSFML_BUILD_NETWORK=OFF \
> >   -DSFML_USE_SYSTEM_DEPS=ON \
> >   -DSFML_INSTALL_PKGCONFIG_FILES=OFF
> > cmake --build build --target install
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Using the `main.cpp` from my first post and the following `CMakeLists.txt`:
> > ```cmake
> > cmake_minimum_required(VERSION 3.0)
> > project(sfml-resize-bug)
> > 
> > set(SFML_STATIC_LIBRARIES TRUE)
> > set(SFML_DIR "$ENV{HOME}/lib/SFML/install/lib64/cmake/SFML")
> > find_package(SFML 2 COMPONENTS graphics REQUIRED)
> > 
> > add_executable(${PROJECT_NAME} main.cpp)
> > target_link_libraries(${PROJECT_NAME} sfml-graphics)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Now the weird resize still happens, but then the window resizes itself to what I specified, so we could say "close enough"?
> 
> I think the weird resize you are talking about is due to a bug in your resize code. Try this instead:
> 
> ```c++
> #include <SFML/Graphics.hpp>
> 
> int main()
> {
>     sf::RenderWindow window(sf::VideoMode(1280, 720, sf::VideoMode::getDesktopMode().bitsPerPixel), "W");
> 
>     while (window.isOpen())
>     {
>         sf::Event event;
>         while (window.pollEvent(event))
>         {
>             if (event.type == sf::Event::Closed)
>                 window.close();
>             else if (event.type == sf::Event::Resized)
>             {
>                 if (event.size.width < 1280)
>                     window.setSize({ 1280, event.size.height });
>                 if (event.size.height < 720)
>                     window.setSize({ event.size.width, 720 });
>             }
>         }
>         window.clear(sf::Color::White);
>         window.display();
>     }
> }
> ```

@Chnossos

**Comment by dogunbound** [comment] 2023-03-21 02:49
> 

Doesn't matter. This fix is not accepted. 
Anyways, what you are saying is if either the x or y direction gets smaller than their respective amount, set the window to 1280 x 720

What I'm saying is if the window size gets smaller than 1280 in the x direction, set the size of the window to 1280 and leave the height alone. Do the same for the y direction.

**Comment by Chnossos** [comment] 2023-03-27 16:09
Using...
```cpp
                if (event.size.width < 1280)
                    window.setSize({ 1280, event.size.height });
                if (event.size.height < 720)
                    window.setSize({ event.size.width, 720 });
```
does the same thing as my original problem without the proposed fix (i.e. resizing width make the window grow in height a lot, then it stays like this, see "Actual behavior" in my OP).

Using...
```cpp
                if (event.size.width < 1280 || event.size.height < 720)
                    window.setSize({ 1280, 720 });
```
mitigate the problem because now the window goes back to 720px in height once I release the handle (but I agree that it should go back to the height it was before attempting to resize width, so it's not perfect either).

**Comment by dogunbound** [comment] 2023-04-14 21:32
Had to close #2518 because they weren't accepting 2.6.x changes anymore. #2519 is up to replace it.

**Comment by ChrisThrasher** [comment] 2023-04-27 20:36
#2519 has been implemented on all OSes. Please try out the new `setMinimumSize()` and `setMaximumSize()` APIs to confirm they fix your problem.

**Comment by dogunbound** [comment] 2023-05-04 18:50
Sweet! We can close this issue once that pull request is merged!

<3

**Closed** 2023-05-12 20:36 UTC
Labels: bug, m:sfml-window, p:linux
