### ISSUE TITLE
[Win] sf::Event::JoystickMoved wrongly triggered

### ISSUE THREAD

**Issue by Bastl34** [SFML/SFML#975] opened 2015-09-24 23:39 UTC
Hi,

there is a bug relating to the `sf::Event::JoystickMoved` event.
I connected a xbox one controller to my Windows 10 Pc.
If I press a button on the controller: the `sf::Event::JoystickMoved` will be triggered on different axes with some random value (but I did not touch any axis).

(It does not appear on a speed link xInput controller)

**Comment by Bromeon** [comment] 2015-09-25 08:35
Please provide a [minimal and complete example](http://en.sfml-dev.org/forums/index.php?topic=5559.msg36368#msg36368). For the future, it would be nice if you could open a thread on the forum first, and only an issue as soon as the bug is confirmed. Especially regarding XBox controllers, there are some known issues, have you had a look at the corresponding forum topics?

**Comment by Bromeon** [comment] 2015-11-29 16:51
Any update on this issue? Reproducible code and a comprehensible problem description (especially after consulting known XBox controller problems) is really required.

**Comment by binary1248** [comment] 2016-10-02 12:44
@Bastl34 can you provide a minimal and complete example? If this behaviour is reproducible, we would like to see if others can reproduce it independently as well in order determine the cause and to come up with a fix.

If nobody else can reproduce the issue, we'll have to consider closing this.

**Comment by binary1248** [comment] 2016-10-15 15:30
Since it's been 2 weeks without any feedback, I'll close this issue for now. Feel free to re-open it if there is more information available.

**Closed by binary1248** 2016-10-15 15:30 UTC
Labels: bug, m:sfml-window, p:windows, s:undecided
