### ISSUE TITLE
Compilation fails due to warning treated as error: unused variable ‘key' 

### ISSUE THREAD

**Issue by MartensCedric** [SFML/SFML#1998] opened 2022-02-09 18:53 UTC
## Subject of the issue

Describe your issue here.

## Your environment

* Ubuntu 18
* SFML source latest
* GCC 11.1

## Steps to reproduce

Git clone the SFML repo
```
mkdir build
cd build
cmake ..
make
```
## Expected behavior

Successful compilation

## Actual behavior

```
[ 45%] Building CXX object src/SFML/Network/CMakeFiles/sfml-network.dir/SocketSelector.cpp.o
[ 46%] Building CXX object src/SFML/Network/CMakeFiles/sfml-network.dir/TcpListener.cpp.o
[ 47%] Building CXX object src/SFML/Network/CMakeFiles/sfml-network.dir/TcpSocket.cpp.o
[ 48%] Building CXX object src/SFML/Network/CMakeFiles/sfml-network.dir/UdpSocket.cpp.o
[ 49%] Building CXX object src/SFML/Network/CMakeFiles/sfml-network.dir/Unix/SocketImpl.cpp.o
[ 50%] Linking CXX shared library ../../../lib/libsfml-network.so
[ 50%] Built target sfml-network
Scanning dependencies of target sfml-graphics
[ 51%] Building CXX object src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/BlendMode.cpp.o
[ 52%] Building CXX object src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/Font.cpp.o
/home/username/Programming/SFML/src/SFML/Graphics/Font.cpp: In member function ‘void sf::Font::setSmooth(bool)’:
/home/username/Programming/SFML/src/SFML/Graphics/Font.cpp:478:30: error: unused variable ‘key’ [-Werror=unused-variable]
         for (auto& [key, page] : m_pages)
                              ^
cc1plus: all warnings being treated as errors
src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/build.make:94: recipe for target 'src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/Font.cpp.o' failed
make[2]: *** [src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/Font.cpp.o] Error 1
CMakeFiles/Makefile2:296: recipe for target 'src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/all' failed
make[1]: *** [src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/all] Error 2
Makefile:170: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by vittorioromeo** [comment] 2022-02-10 00:12
I can reproduce with a very old version of GCC:
https://gcc.godbolt.org/z/j4PGz7eW3

**Comment by MartensCedric** [comment] 2022-02-10 00:19
Easiest way to reproduce. 

Make a github action CI for an SFML project that builds locally

```
name: Ubuntu 18.04

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev udev libudev-dev libopenal-dev vorbis-tools libvorbis-dev libflac-dev

    - name: Run CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}

```

**Comment by MartensCedric** [comment] 2022-02-10 00:20
I updated to Ubuntu 20 and this solved my issue.

**Comment by vittorioromeo** [comment] 2022-02-10 00:38
Glad to hear that. I did a brief Google search and it seems that Ubuntu 18 uses an old version of GCC (7.x). I am not sure if we want to support that. @eXpl0it3r @Bromeon thoughts? We should probably decide on a minimum compiler version.

**Comment by vittorioromeo** [comment] 2022-02-10 13:43
> Here, the gcc version was newer though; maybe it was not accurate?

I don't think it was. I cannot reproduce the issue with GCC 11, but I can with GCC 7.

GCC 7.1 is from 2017. GCC 7.4, shipping with Ubuntu 18, is from 2018.

**Comment by MartensCedric** [comment] 2022-02-10 13:46
hmm I was using Ubuntu 18 but I had separately installed gcc 11. When I
would run gcc -v I would get 11.1. I did also have 7 installed it was not
th gcc it would pick up a new terminal window. Looks like it was picking up
gcc 7?

**Comment by eXpl0it3r** [comment] 2022-02-10 13:57
Maybe you didn't install `g++` v11 and were still on v7

> We should probably decide on a minimum compiler version.

Would make sense to me. We'd also have to point out that VS 2017 is no longer supported etc.
What's the minimal version of GCC that has full C++17 support?

**Comment by MartensCedric** [comment] 2022-02-10 14:23
That's probably it! I completely forgot to also check g++, I checked gcc...
i think that's it!

**Comment by eXpl0it3r** [comment] 2022-03-10 13:38
I'll close this for now and add a note that we'll need to document somewhere the minimum supported compiler versions

**Closed by eXpl0it3r** 2022-03-10 13:38 UTC
Labels: not an issue
