### ISSUE TITLE
[RPMLint] Program returns random data in a function (RenderTarget.cpp)

### ISSUE THREAD

**Issue by susnux** [SFML/SFML#935] opened 2015-08-01 14:52 UTC
I am trying to build SFML 2.3.1 for openSUSE, but build failed with RPMLint report:

> I: Program returns random data in a function
> E: sfml2 no-return-in-nonvoid-function SFML-2.3.1/src/SFML/Graphics/RenderTarget.cpp:56, 67

Because the functions:
sf::Uint32 factorToGlConstant(sf::BlendMode::Factor blendFactor)
and 
sf::Uint32 equationToGlConstant(sf::BlendMode::Equation blendEquation)
do not have a default return.

I use a simple patch, if you want to, you can use it.
Direct link to patch: https://build.opensuse.org/source/games/sfml2/fix-upstream-no-return-in-nonvoid-function.patch?rev=24d1fc187f50849c3826c094f028057b

Edit: Updated link to patch.

**Comment by TankOs** [comment] 2015-08-03 06:57
Good catch. A pull request would help us to integrate this easier, though. ;)

**Comment by Bromeon** [comment] 2015-08-03 07:56
For the future, please refer to the [contribution guidelines](http://www.sfml-dev.org/contribute.php) before creating issues.

-----

I don't get why C++ compilers and static analyzers are always stupid when it comes to `switch` statements. In Java, for example, they're much more useful. **We obviously handle every valid case**, there's definitely no need to emit an error for correct C++ code.

I'm totally aware that you *can* force an integer into an enum that is not listed as an enumerator, but that's absolutely not a problem of the code that handles the switch statement. I don't think we should add silly code to catch undefined behavior -- or if we do, at least in the form of a precondition/assert.

Because one big problem that `default` introduces is that it catches all the cases even if they aren't handled. That is, if the enum grows in the future, the few *smart* static analyzers/compilers can tell you that you forgot to adapt the `switch` statement accordingly. However, when there's a `default` label, they think you intended to handle them, and you get runtime errors instead.

**Comment by eXpl0it3r** [comment] 2015-08-03 08:21
The error is valid in my opinion and the error is not directly about the switch statement.

The issue is that not **all possible** code paths will end up returning a value for the function. Sure, we don't call the function with a different value than the ones in the enum, yet an enum is basically just an integer and it's legal C++ code to cast and pass in any integer.

The problem right now is that, *if* someone would ever pass in an integer that is not in the enum, the function will probably silently fail and return random data. Sure you can argue that the user asked for UB when passing in a wrong value, but failing silently is in my opinion bad.

On IRC it was suggested to put an assert after the switch statement. And one could still add a return, even though it then would never be reached.

**Comment by TankOs** [comment] 2015-08-03 08:39
"Better safe than sorry" is everything I want to say. :)

**Comment by Bromeon** [comment] 2015-08-03 16:46
> an enum is basically just an integer and it's legal C++ code to cast and pass in any integer.

No -- it's unspecified behavior, meaning you can't portably rely on a behavior. And you can especially not pass in any integer, the range of valid ones is clearly defined by the standard. This apart from the fact that it makes no sense in most cases, as the whole point of using `enum` is to define a finite, bounded set of states.

> The problem right now is that, if someone would ever pass in an integer that is not in the enum, the function will probably silently fail and return random data. Sure you can argue that the user asked for UB when passing in a wrong value, but failing silently is in my opinion bad.

Yes, it's bad, but as I mentioned, it's not the responsibility of this function to handle user errors. We don't do this in all the other functions that work with enums, either. And if the compilers and static analyzers didn't complain here, nobody would even remotely consider this an issue :wink:

Anyway, there's probably no way around this, we have to comply with the tools. Because it's not the first time I have been annoyed by this circumstance, I even have some code that deals with it, I can write a PR if you like :grinning:

**Comment by MarioLiebisch** [comment] 2015-08-03 19:56
Wouldn't call it a problem to create dummy return values for code analyzers (probably with an added assert).

Actually MSVC only detects two such issues in SFML, both with the `...ToGlConstant()` helpers. There are a few more warnings (deprecated or unsave calls) though.

**Comment by TankOs** [comment] 2015-08-04 05:45
IMHO it will still make the code safer. It doesn't cost us anything but will especially make refactorings easier, IF that happens.

**Comment by susnux** [comment] 2015-08-04 23:47
My personal opinion is: In a library I would ever add a default, in a normal program it is not a problem (you can be safe, if you not use a cast). But in a library you do not know how stupid your user is ;-)
And it adds more security, without much more work.
But that is only my opinion and  I am not a SFML-developer.

PS: I think(!) even with a default you can check if you missed an enum case in switch with this gcc flag:
```-Wswitch-enum```

**Comment by TankOs** [comment] 2015-08-05 06:40
@susnux This patch should be alright. Can you be bothered with creating a PR, so that we can apply it easily together with your author info?

**Comment by Bromeon** [comment] 2015-08-05 20:58
> [MarioLiebisch] Wouldn't call it a problem to create dummy return values for code analyzers (probably with an added assert).
> [TankOs] It doesn't cost us anything 

Yes, it does:

> [Nexus] Because one big problem that `default` introduces is that it catches all the cases even if they aren't handled. That is, if the enum grows in the future, the few *smart* static analyzers/compilers can tell you that you forgot to adapt the `switch` statement accordingly. However, when there's a `default` label, they think you intended to handle the missing cases, and you get runtime errors instead.

We take this disadvantage only to satisfy a badly-written tool, and we write redundant code to "fix" something that has been 100% correct, always.

-----

> @susnux This patch should be alright. Can you be bothered with creating a PR, so that we can apply it easily together with your author info?

The patch is not good, it still ignores the error. `sf::err()` is only diagnostic output, the program continues to run even in Debug mode.

As mentioned above:
> Because it's not the first time I have been annoyed by this circumstance, I even have some code that deals with it, I can write a PR if you like :grinning: 

But I want to be sure that you're fully aware of the disadvantages, which *do* exist, as outlined above. Some further opinions would be nice, too.

**Comment by susnux** [comment] 2015-08-05 21:17
@Bromeon No, it costs you nothing. I tried it myself and even if you have a "default", a simple gcc flag warns about missing case for enum.
See yourself:
http://pastie.org/10332164


> The patch is not good, it still ignores the error. sf::err() is only diagnostic output, the program continues to run even in Debug mode.

Hm, that's a matter of opinion. In my opinion the user (better the developer) should be informed about the error, but for the user the program using the library should not crash.
But that is only my opinion.

**Comment by TankOs** [comment] 2015-08-06 06:35
@Bromeon 
I wonder why you always bring `default:` to the table. The patch is not adding `default:` to the switch, it's just adding a return *after* the switch, so that all possible code paths have a return statement (yes, I know, the path is not possible because all cases are handled, but lint tools often do not go that far, and I still think that it even increases readability).

That means you'll still be warned if there's a new case value that's not handled in the switch.

**Comment by TankOs** [comment] 2015-08-06 06:37
Regarding the error message: Right now, we are doing *nothing*, and you said yourself that the path will never be reached. This is a safe guard, that will at least print something out if the rare case happens that the switch did not handle a case (aka an invalid value was passed to the function).

I'm fine with adding an assert on top.

**Comment by Bromeon** [comment] 2015-08-06 07:08
> The patch is not adding `default:` to the switch, it's just adding a return after the switch

That's true, sorry, I was still thinking in `default` terms. In languages like Java where you get heavy IDE support, I've seen it quite a lot that people rely on these warnings and simply forget to adapt switch/case statements when a `default` "eats" everything.

> I tried it myself and even if you have a "default", a simple gcc flag ("-Wswitch-enum") warns about missing case for enum.

But that's also broken; in fact, the whole analysis around switch/case is awful in C++. There's no point in giving a warning when multiple cases are put together. Remember that the intention of `default:` is explicitly "all the other cases", not "all the invalid cases that don't appear in correct C++".

> In my opinion the user (better the developer) should be informed about the error, but for the user the program using the library should not crash.

Informing the developer would be achieved with simply adding `assert(false)` -- it doesn't do anything for the user, but it helps the developer find the problem immediately.

-----

Don't forget that this whole topic is something we recently discussed, and the conclusion was to leave things as-is for the moment, but to agree on an library-wide approach regarding assertions and checks in the future, instead of handling every request on its own. See [this post](http://en.sfml-dev.org/forums/index.php?topic=18170.msg130969#msg130969) in particular.

**Comment by eXpl0it3r** [comment] 2015-08-06 11:38
So do we close this or keep it open or close it and create an issue on "refactoring" assert usage?

**Comment by TankOs** [comment] 2015-08-06 12:57
> on an library-wide approach regarding assertions and checks in the future, instead of handling every request on its own

That's correct, and mainly the reason why I did not come up with "Please add an assert on top". What do you guys think of just keeping this simple, apply the patch + an assert on top? It makes sense now, and it'll probably make sense when we apply a library-wide strategy for error reporting.

**Comment by Bromeon** [comment] 2015-08-06 13:00
> What do you guys think of just keeping this simple, apply the patch + an assert on top? It makes sense now, and it'll probably make sense when we apply a library-wide strategy for error reporting.

Okay :grinning: 
"Let's not open an office here" :stuck_out_tongue:

**Comment by TankOs** [comment] 2015-08-07 07:00
:D

**Comment by susnux** [comment] 2015-08-13 22:20
I have created a pull request to close this issue, I applied the patch and added an assert.
I think this was the common consent.

**Comment by eXpl0it3r** [comment] 2015-08-24 11:51
Merged in 0f1dc5a7542a1794412a02744ab6afc1810bab17 on branch 2.3.x

**Closed by eXpl0it3r** 2015-08-24 11:51 UTC
Labels: bug, m:sfml-graphics, s:accepted
