### ISSUE TITLE
Problems with using `sf::String`s and wide strings (`std::wstring`)

### ISSUE THREAD

**Issue by nedoxff** [SFML/SFML#2047] opened 2022-03-16 20:35 UTC
## Subject of the issue

At one point in making of my game I needed to test Russian text. I initially tried `L"string here"`, which turned out to work only on one compiler (MinGW). 😅 

## Your environment

* Your OS / distro / window manager used: Windows 10, 64bit, build 21H2
![изображение](https://user-images.githubusercontent.com/65343244/158676400-e4ba12a4-c13d-49b5-b87d-013d10c15e4a.png)

* Your version of SFML (2.5.0, git master, etc): 2.6 (branch `2.6.x`, tag `3315456dc32e2da000145bb7f97083154806b59b`) and 3.0 (branch `master`, tag `5c9b571c70eeb0171affbce08b005a1d65765115`)
* Your compiler and compiler version used: MSVC (`19.31.31104.0`), Clang and MinGW (GNU 11.2.0, bundled with CLion)
Clang versions:
![изображение](https://user-images.githubusercontent.com/65343244/158677019-9760c6a4-f172-4a75-86a1-88b88463a22c.png)

* Special compiler flags used: none

Here is the ZIP archive I used:  [SFMLTest.zip](https://github.com/SFML/SFML/files/8270902/SFMLTest.zip)
**MD5 Checksum:** `4c99ca98215ccc919181fd2dd8d24c79`

Here is just the `main.cpp` without any resources:
```cpp
#include <iostream>
#include <SFML/Graphics.hpp>
int main() {
	sf::RenderWindow window(sf::VideoMode(500, 100), "SFML Wide String Text Example");

	sf::Font font;
	if(!font.loadFromFile("C:\\Windows\\Fonts\\Arial.ttf"))
	{
		std::cerr << "uh oh! (failed loading font)" << std::endl;
		return 1;
	}

	sf::Text text;
	text.setCharacterSize(48);
	text.setString(L"test test тест");
	text.setFont(font);

	while(window.isOpen())
	{
		sf::Event event{};
		while(window.pollEvent(event))
		{
			if(event.type == sf::Event::Closed)
				window.close();
		}

		window.clear();
		window.draw(text);
		window.display();
	}
	return 0;
}
```

## Expected behavior

The code compiles successfully and creates a window with a text.

MinGW produces the expected behavior:
![изображение](https://user-images.githubusercontent.com/65343244/158685885-9e48208b-6ab6-4be6-b582-1f6622f833f6.png)

## Actual behavior

With MSVC it creates a window, but the text looks.. wrong..
![изображение](https://user-images.githubusercontent.com/65343244/158685458-0b0a035a-c891-4e5f-8bfe-bce1ba8415a9.png)

**Comment by eXpl0it3r** [comment] 2024-05-09 08:32
I cannot reproduce this problem, neither in SFML 3 nor SFML 2.

Not sure if you've used some special setting for the string handling. I know MSVC provides some unicode options, did you enable/disable any of them?  
The important part with such options is, that you use the same settings for both your application, as well as when build SFML (and potentially SFML's dependencies).

SFML 3 example code:

```cpp
#include <iostream>
#include <SFML/Graphics.hpp>
int main() {
	sf::RenderWindow window(sf::VideoMode({ 500, 100 }), "SFML Wide String Text Example");

	sf::Font font;
	if (!font.loadFromFile("C:\\Windows\\Fonts\\Arial.ttf"))
	{
		std::cerr << "uh oh! (failed loading font)" << std::endl;
		return 1;
	}

	sf::Text text{font};
	text.setCharacterSize(48);
	text.setString(L"test test тест");

	while (window.isOpen())
	{
		while (auto event = window.pollEvent())
		{
			if (event.is<sf::Event::Closed>())
				window.close();
		}

		window.clear();
		window.draw(text);
		window.display();
	}
}
```

Are you still experiencing this issue, @nedoxff?

**Comment by eXpl0it3r** [comment] 2024-05-12 17:56
I'll close this for now. Feel free to reopen with additional details.

**Closed by eXpl0it3r** 2024-05-12 17:56 UTC
Labels: bug, m:sfml-system, p:windows

**Comment by nedoxff** [comment] 2024-06-01 19:09
hi! sorry for the late response. 😅 

i think the issue was caused by some specific flag i enabled via cmake or visual studio. unfortunately my setup has significantly changed since then, so i probably won't be able to reproduce this either.

i'm pretty sure the issue is fixed or it wasn't SFML's fault to begin with. thank you for looking at it!
