### ISSUE TITLE
Website not accessible in Turkey

### ISSUE THREAD

**Issue by DenizBasgoren** [SFML/SFML#1646] opened 2020-02-26 03:56 UTC
When I try to enter your website, i get redirected somewhere.

http://88.255.216.16/landpage?op=1&ms=http://sfml-dev.org/

If I try to go to /documentation/2.5.1, then I get the following error on my Firefox:

SSL_ERROR_RX_RECORD_TOO_LONG

Could you please host your documentation elsewhere, like for example on Github pages?

**Comment by LaurentGomila** [comment] 2020-02-26 05:35
Duplicate of https://github.com/SFML/SFML-Website/issues/137

**Closed by LaurentGomila** 2020-02-26 05:35 UTC
